### ISSUE TITLE
Node 0.10 and 0.12 support

### ISSUE THREAD

**Issue by fabiosantoscode** [terser-js/terser#132]
It's been a while since these node versions have been deprecated. We should seriously think whether we need to keep supporting them. Node 8 came out more than a year ago!

@kzc what do you think of us dropping support for these node versions?

**Comment by kzc** [comment]
I see no harm in continuing to support Node 0.10 and 0.12. Having them as a target is also a good way to determine that Terser is ES5 compatible for old browser targets.

**Comment by fabiosantoscode** [comment]
Got it
