### ISSUE TITLE
#129 not fixed correctly

### ISSUE THREAD

**Issue by kzc** [terser-js/terser#136]
Please reopen #129. 

All the failing test cases listed still do not work and there are a number of regressions in non-tagged template literals.

* https://github.com/terser-js/terser/issues/129#issuecomment-431609433
* https://github.com/terser-js/terser/issues/129#issuecomment-431611171

The [ES2018 revision of illegal escape sequences within tagged template literals](https://github.com/terser-js/terser/issues/129#issuecomment-430666089) has not been implemented.

**Comment by kzc** [comment]
This test is ill-formed. The `undefined` sent to stdout in this test is due to the function `x` not returning anything:
```
template_strings: {
    input: {
        function x() {}
        console.log(String.raw`\u`);
        console.log(x`\u`);
    }
    expect_stdout: [
        "\\u",
        "undefined"
    ]
    node_version: ">=4"
}
```
Perhaps the following was intended?
```
$ cat tag.js
function x(strings) {
    console.log(strings.raw[0]);
}
x`\u`;
```
```
$ node-v10.4.1 tag.js
\u
```
Also please include an `expect:` clause so that the test can validate the generated code on all Node versions - even if only Node 10+ can run the `expect_stdout` portion of the test.

**Comment by fabiosantoscode** [comment]
I think it's fixed now. Added expect_exact clause, too.

**Comment by kzc** [comment]
@fabiosantoscode There are still a number of issues. See additional comments in #129. Also noticed that one of your tests failed.

This process would be infinitely easier if development for complex new features were to take place in a Pull Request and only merged to `master` if verified by another maintainer and all the Travis CI tests are green.

**Comment by fabiosantoscode** [comment]
Nope, not yet. If you input "FAIL\u" you get "FAIL\0". I'll have another look

**Comment by fabiosantoscode** [comment]
I agree. I'll start using that workflow

**Comment by fabiosantoscode** [comment]
I've created a branch invalid-unicode-escape-sequences but opening PRs isn't working for some reason.

**Comment by edmorley** [comment]
> I've created a branch invalid-unicode-escape-sequences but opening PRs isn't working for some reason.

A GitHub incident is in progress:
https://status.github.com/messages

**Comment by fabiosantoscode** [comment]
Thanks @edmorley, I caught up to that on twitter :D
