### ISSUE TITLE
Please use Pull Requests for everything merged to master

### ISSUE THREAD

**Issue by kzc** [terser-js/terser#138]
**Bug report or Feature request?**

development process bug

```
commit 211d829e65008f029f36058aefc60ca6d3985580
Author: Fábio Santos <fabiosantosart@gmail.com>
Date:   Tue Oct 23 21:58:47 2018 +0100

    add missing module

commit 1993f8e89e864d8219d875dcca6d48155e39e916
Author: Fábio Santos <fabiosantosart@gmail.com>
Date:   Tue Oct 23 21:46:05 2018 +0100

    add missing module

commit 58d6d326c32d754d46db23a78b0dd25166030fd7
Author: Fábio Santos <fabiosantosart@gmail.com>
Date:   Tue Oct 23 21:43:27 2018 +0100

    speed tests up by parallelising them
```

`master` should always be in an error-free test state so that anyone may create a PR at any point and have a reasonable expectation that it would run the test suite correctly.

Using PRs for everything committed to `master` - even changes to the build system - would guarantee that. Only PRs with green test state could be merged to master.

**Comment by kzc** [comment]
Further, to aid debugging and the use of `git bisect`, every green PR should have its commits squashed when merging to master. Any commit on master should be be able to run `npm test` cleanly.

**Comment by fabiosantoscode** [comment]
Got it. I'll use PRs from now on.

**Comment by edmorley** [comment]
> Got it. I'll use PRs from now on.

This didn't use a PR?
https://github.com/terser-js/terser/commit/5f40c179c0201372529d5ce3e06ba2790df5d02c
