### ISSUE TITLE
`npm test` reports success despite compress test failure

### ISSUE THREAD

**Issue by kzc** [terser-js/terser#151]
**Bug report or Feature request?**

bug

**Version (complete output of `terser -V`)**

master 3c59d40c1a16960df8c658028074ddd6aa730652

A bug was introduced in a compress test in PR #150.

Note that Travis reporting success for this PR: 

https://travis-ci.org/terser-js/terser/builds/448185727?utm_source=github_status&utm_medium=notification

despite a compress test failure: 

https://travis-ci.org/terser-js/terser/jobs/448185730#L518-L528

**Comment by kzc** [comment]
Can we revert `test/run-tests.js` to this version which is known to work?

https://github.com/terser-js/terser/blob/217111950ff5cc325317a3f2a8b55f74ac0b4ec5/test/run-tests.js

**Comment by fabiosantoscode** [comment]
Thanks for the report
