### ISSUE TITLE
bug: `turn i += 1 into i++`

### ISSUE THREAD

**Issue by kzc** [terser-js/terser#155]
**Bug report or Feature request?**

bug

**Version (complete output of `terser -V`)**

terser 3.10.8

**Complete CLI command or `minify()` options used**

**Expected**

```
$ echo 'for (var i = "A"; i.length < 4; i += 1); console.log(i);' | node
A111
```

**Actual** (incorrect) Terser result:

```
$ echo 'for (var i = "A"; i.length < 4; i += 1); console.log(i);' | terser -c | node
NaN
```
```
$ echo 'for (var i = "A"; i.length < 4; i += 1); console.log(i);' | terser -c
for(var i="A";i.length<4;++i);console.log(i);
```

This was just the first bug that came to mind. There are other (different) bug scenarios that I did not list.

5f40c179c0201372529d5ce3e06ba2790df5d02c is not a safe optimization. For it to work properly it would have to perform escape analysis on the variable in question to ensure it always contains a `Number` throughout its lifetime. This is not trivial in the general case. One would have to track all updates and assignments for the variable in question. `reduce_vars` can be used for this purpose.

Please either revert 5f40c179c0201372529d5ce3e06ba2790df5d02c or put it behind a new `unsafe_increment` option, defaulting to `false`. In general every new optimization should be behind a new option so it may be disabled without affecting previously existing optimizations.

@fabiosantoscode It's unfortunate that using Pull Requests for reviews was abandoned in favor of merging directly to master. If a PR was created and there was a review period of a few days then someone could have had the opportunity to point out the bug before it was committed and released.

**Comment by kzc** [comment]
Related efficiency issue: https://github.com/terser-js/terser/commit/5f40c179c0201372529d5ce3e06ba2790df5d02c#r31124346

**Comment by fabiosantoscode** [comment]
I'll remove the feature, then.
