### ISSUE TITLE
More advanced dead code elimination

### ISSUE THREAD

**Issue by rmacklin** [terser-js/terser#160]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V`)**

3.10.11

**`terser` input**

```js
const {minify} = require("terser");
const source = `
(function(t) {
  if (!t) {
    const e = s("foo");
    t = e || p.bar
  }
  return new k(o(t))
}
)(true).create("Baz", {})
`;
minify(source, {toplevel: true, compress: {passes: 5}}).code;
```

[REPL](https://repl.it/repls/FloweryAnyLightweightprocess)

**`terser` output or error**

```js
var a;(a=!0,a||(a=s("foo")||p.bar),new k(o(a))).create("Baz",{});
```

**Expected result**

```js
new k(o(!0))).create("Baz",{});
```

Terser inlines the immediately invoked function expression (which is good), but after it does that it keeps the body of the `if` block from the original source, which is unreachable code (since the IIFE parameter `t` is passed as `true`, `if (!t) { ... }` is equivalent to `if (false) { ... }`).

I thought this would be fixed by increasing the number of passes, but increasing the number of passes didn't change the output.

**Comment by rmacklin** [comment]
I also tried some simpler versions to see Terser's behavior:

Moving the IIFE parameter into the function body:
```js
const {minify} = require("terser");
const source = `
(function() {
  var t = true
  if (!t) {
    const e = s("foo");
    t = e || p.bar
  }
  return new k(o(t))
}
)().create("Baz", {})
`;
minify(source, {toplevel: true, compress: {passes: 5}}).code;
```

did not help; it produced the same output:
```
var a;(a=!0,a||(a=s("foo")||p.bar),new k(o(a))).create("Baz",{});
```

[REPL](https://repl.it/repls/NaiveRudeWorkers)

I also experimented with removing the IIFE:

```js
const {minify} = require("terser");
const source = `
var t = true
if (!t) {
  const f = r("foo");
  t = f || p.bar
}
console.log('hi')
`;
minify(source, {toplevel: true, compress: {passes: 5}}).code;
```

which still included the dead code:
```js
var o=!0;o||(o=r("foo")||p.bar),console.log("hi");
```

[REPL](https://repl.it/repls/PerfectFlippantProtools)

Note, however, that if I just change the above example from `!t` to `!true`:
```js
const {minify} = require("terser");
const source = `
var t = true;
if (!true) {
  const f = r("foo");
  t = f || p.bar
}
console.log('hi')
`;
minify(source, {toplevel: true, compress: {passes: 5}}).code;
```

it does remove the dead code:
```js
console.log("hi");
```

[REPL](https://repl.it/repls/SturdyGargantuanRuntimeerror)

Am I missing something that makes it unsafe to eliminate the `if` block when the input is:
`var t = true; if(!t) { ... }`
rather than
`var t = true; if(!true) { ... }`
?

**Comment by kzc** [comment]
It's not as simple a problem as it seems. Uglify/Terser doesn't step through a program as a CPU would, nor does it use [SSA](https://en.wikipedia.org/wiki/Static_single_assignment_form). It performs a form of constant propagation based on certain assumptions. Any reassignment of a variable causes `reduce_vars` to disqualify it from being considered a constant - **regardless of wherever it takes place**.
```
$ cat test.js
(function(t) {
    if (!t) {
        const e = s("foo");
        t = e || p.bar;        // <-------- reassignment
    }
    return new k(o(t));
})(true).create("Baz", {});
```
```
$ cat test.js | terser -c passes=3
(function(t){return t||(t=s("foo")||p.bar),new k(o(t))})(!0).create("Baz",{});
```
Notice what happens when you convert the input to an SSA-like form:
```
$ cat t2.js
(function(t) {
    if (!t) {
        const e = s("foo");
        var t2 = e || p.bar;
    }
    return new k(o(!t ? t2 : t));
})(true).create("Baz", {});
```
```
$ cat t2.js | terser -c passes=3
new k(o(!0)).create("Baz",{});
```

**Comment by rmacklin** [comment]
> Any reassignment of a variable causes `reduce_vars` to disqualify it from being considered a constant - **regardless of wherever it takes place**

Thanks for the explanation @kzc! That makes sense. Do you see this as something that's not likely to change?

I'm curious if you think optimizing `!t` -> `false` could be done earlier in the compilation process such that the entire block gets treated as dead code before the unreachable reassignment instructs the compiler that `t` shouldn't be treated as constant. Or I guess - does it have to matter that `t` is not a constant? Even code like
```js
var t = true;
if (!t) {
  t = 'unreachable'
}
t = 'something else'
```
— where `t` is definitely not constant — still has an if block that could be eliminated.

And to be clear, I appreciate the workaround of rewriting the code in SSA form (thanks for sharing it) - but when the code in question exists in third party dependencies there's a lot more friction behind that.

**Comment by kzc** [comment]
> does it have to matter that t is not a constant?

>> Uglify/Terser doesn't step through a program as a CPU would, nor does it use SSA.

> Do you see this as something that's not likely to change?

It's a volunteer effort. Pull requests to implement SSA are welcome.

**Comment by rmacklin** [comment]
Ok, great. And sorry if my last comment came off poorly - that was not my intention. I just wanted to ask if you thought this type of thing would be a welcome change or not. In my experience with open source projects, sometimes the maintainers who know a lot about the internals and the current direction of the project may respond to that sort of question with good reasons why the change is not likely to be accepted at this time.

**Comment by rmacklin** [comment]
Also, out of curiosity, I tried this similar example that uses ES2015 default parameters:

```js
const {minify} = require("terser");
const source = `
(function(t = s('foo') || p.bar) {
  return new k(o(t))
})(true)
`;
minify(source, {toplevel: true, compress: {passes: 5}}).code;
```

which gets minified to:
```
!function(n=s("foo")||p.bar){new k(o(n))}(!0);
```

[REPL](https://repl.it/repls/UnconsciousAuthenticMegahertz)

Interestingly, here the IIFE body didn't get inlined like in the original example. I'm wondering why that is, although the bigger question I have is if there are different reasons that this example doesn't minify to `return new k(o(!0))`. Or, how does the constant propagation work with regards to knowing/not knowing when the default value of `t` can be discarded (because the IIFE parameter is not `undefined`)?

**Comment by kzc** [comment]
Take a look for yourself. The core code is in a [dozen or so files](https://github.com/terser-js/terser/tree/master/lib). `lib/compress.js` is where the AST optimizations happen. 

ECMAScript is complicated. Every new Terser compiler optimization has the potential to introduce errors. It is not uncommon for bugs in new features to take dozens of releases to shake out.

At the end of the day, minification correctness and terser speed is more important than code optimizations: https://github.com/terser-js/terser#terser-fast-minify-mode

**Comment by fabiosantoscode** [comment]
Looks like we can't optimise this, since it's a rare case it would cost us speed for little benefit. Closing.
