### ISSUE TITLE
Unexpected top_retain/reduce_vars/unused results

### ISSUE THREAD

**Issue by opichals** [terser-js/terser#161]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V`)**

3.10.11

**Complete CLI command or `minify()` options used**

See [the failing test commit](https://github.com/terser-js/terser/commit/cb23672efe62df0615eac60b01926b9b322c0522).

When the `top_retain` function is called twice the output is fine but when it is only called once then the output is not what one would expect.

**Comment by kzc** [comment]
Please test against #162 and report your findings.

**Comment by opichals** [comment]
@kzc Thank you! Confirmed, the #162 fixes this issue.
