### ISSUE TITLE
Crashes node with JavaScript heap out of memory

### ISSUE THREAD

**Issue by CarterLi** [terser-js/terser#164]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V`)**

terser 3.10.11

Found on node v10.13.0 (ubuntu); verified on node v11.1.0 (macOS)

**Complete CLI command or `minify()` options used**

I'm using terser with [terser-webpack-plugin](https://webpack.js.org/plugins/terser-webpack-plugin/#src/components/Sidebar/Sidebar.jsx),

```
const TerserWebpackPlugin = require('terser-webpack-plugin');
minimizer: [
  new TerserWebpackPlugin({
    test: /(vendors|runtime~main).*\.js(\?.*)?$/i
  }),
],

```
```
  optimization: {
    runtimeChunk: true,
    splitChunks: {
      cacheGroups: {
        commons: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors',
          chunks: 'all',
        },
      }
     }
  }
```

**`terser` input**

Can't provide a minimal test case, but I'm minifying 3rd-party libraries including Angular 7

**`terser` output or error**

```
● Webpack █████████████████████████ additional chunk assets processing (91%)



<--- Last few GCs --->

[41382:0x104002400]   109170 ms: Scavenge 1306.3 (1416.4) -> 1305.5 (1416.4) MB, 6.1 / 0.0 ms  (average mu = 0.217, current mu = 0.137) allocation failure
[41382:0x104002400]   109192 ms: Scavenge 1306.4 (1416.4) -> 1305.6 (1416.4) MB, 7.4 / 0.0 ms  (average mu = 0.217, current mu = 0.137) allocation failure
[41382:0x104002400]   109209 ms: Scavenge 1306.5 (1416.4) -> 1305.7 (1416.4) MB, 6.8 / 0.0 ms  (average mu = 0.217, current mu = 0.137) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x296c1269d949 <JSObject>
    0: builtin exit frame: lastIndexOf(this=0x296c63c11401 <Very long string[2782918]>,0x296c06baa819 <String[1]\: \n>,0x296c63c11401 <Very long string[2782918]>)

    1: L(aka L) [0x296c0a513921] [/Users/Carter/sharplook/node_modules/terser/dist/bundle.js:44] [bytecode=0x296c0a558211 offset=15](this=0x296c309025b1 <undefined>)
    2: prepend_comments [0x296c0a513891] [/Users/Carter/sharplook/no...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100039ef7 node::Abort() [/usr/local/bin/node]
 2: 0x10003a0c8 node::FatalTryCatch::~FatalTryCatch() [/usr/local/bin/node]
 3: 0x10016e23b v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10016e1dc v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x10042e8d8 v8::internal::Heap::UpdateSurvivalStatistics(int) [/usr/local/bin/node]
 6: 0x100430347 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 7: 0x10042dc53 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10042ca39 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x100434937 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x100434984 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x100414d57 v8::internal::Factory::AllocateRawWithImmortalMap(int, v8::internal::PretenureFlag, v8::internal::Map*, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x1004168c5 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
13: 0x1004f4dae v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
14: 0x1005108e7 v8::internal::String::LastIndexOf(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
15: 0x10020870e v8::internal::Builtin_Impl_StringPrototypeLastIndexOf(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
16: 0x804a4acfcdd
```

**Expected result**

Don't crash

**Comment by CarterLi** [comment]
May relate to https://github.com/webpack/webpack/issues/6929 but I'm using terser only in production mode

**Comment by kzc** [comment]
There's no actionable information here. The issue template was not followed and no terser input was provided for a reproduction.

This is most likely a webpack issue, not a terser issue. Your build was likely near the threshold of being out of memory before.  Increase Node memory size or try different options.

Related issue very similar to this report: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/188#issuecomment-349860488

**Comment by CarterLi** [comment]
I tested unminified code generated by webpack with terser. It did work.

I'll close this

**Comment by kzc** [comment]
> I tested unminified code generated by webpack with terser. It did work.

No conclusions can be drawn from that. If you were near the Node.JS memory limit, it may work in development mode and not in production mode. 

And then there's the issue that webpack generates different code for production and development modes. So it's difficult for its users to obtain unminified production output as a test case for Terser. Webpack really ought to have a CLI flag `--no-minify` (as Parcel does) which could be used in production mode to easily discern if there's a webpack issue or a minifier issue.

To create a test case for Terser follow [these instructions](https://github.com/terser-js/terser/issues/120#issuecomment-425979826) and then run webpack in production mode, redirect stderr to a file, and then post that file into a gist.

**Comment by vladimiry** [comment]
Out of memory errors occur quite often If you run a relatively heavy build on Travis / Appveyor CI with free/open-source plans. Here is another relative issue https://github.com/webpack-contrib/terser-webpack-plugin/issues/22.

**Comment by dep** [comment]
I know this isn't a terser-js issue per se, but @CarterLi did you land on any solutions here? I'm having the same issue.

**Comment by CarterLi** [comment]
@dep I split large files into smaller chunks

https://webpack.js.org/plugins/split-chunks-plugin/#optimization-splitchunks

**Comment by dep** [comment]
@CarterLi Thank you so much. This worked!

**Comment by fabiosantoscode** [comment]
@dep could you provide a minimal example of this crash? Then I can reopen the issue.

**Comment by dep** [comment]
It ended up being a `node` memory issue, I fixed it by scoping a param in to node for my build job, like so:

`package.json`:
```
"scripts": {
  "build": "node --max-old-space-size=4069 scripts/build.js",
}
```

Leaving that here for posterity.

**Comment by vladimiry** [comment]
> I fixed it by scoping a param in to node for my build job

This is not a fix but workaround.

**Comment by ngprnk** [comment]
this is not an issue in development mode, this arises in production mode, when it is doing minifying process, not sure if this issued should be closed.

**Comment by steven87vt** [comment]
> @dep I split large files into smaller chunks
> 
> https://webpack.js.org/plugins/split-chunks-plugin/#optimization-splitchunks

As just an FYI, the OP stated they "split large files into smaller chunks". I used the following property to dial in what the minimum chunk size was for my app:
[https://webpack.js.org/plugins/split-chunks-plugin/#splitchunksmaxsize](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunksmaxsize)

After dialing in the precise size requirements down to the nearest hundred bytes, webpack produced a set of chunked .js files which I could then manually analyze. The largest being the culprit in my specific case.

Thanks you OP @CarterLi  for rasing and solving the issue.

**Comment by dadamssg** [comment]
@steven87vt could you describe what the "culprit" was? and how you ultimately fixed that?

**Comment by steven87vt** [comment]
So my short term fix was to set the optimizations.splitChunks.max size option. The result of this is more chunked production files for download. 

The "cluprit" in my case is 8 different developers blazing through spa development not applying best practise to js imports (and the additions to lodash chaining). 

The long term, more detailed fix is using a bundle analyzer to effectively target your applications needs, such as https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/README.md

**Comment by trusktr** [comment]
My experience with UglifyJS and now with Terser, is that they always crash my production builds.


I wish this was recognized as an actual issue.

You see, I can build _**huge**_ C/C++ libs (even if it takes hours) on my dinky 8GB RAM i5 laptop, yet this JS minification stuff crashes after it reaches memory limits (usually after 10-15 minutes in my specific case).

There's obviously room for improvement here, like re-factoring the minifier tool to use an async-chunked method of operation capable of saving chunks on disk (or something, I'm just imagining).

On a MacBook pro, my production build needs 10GB of memory to succeed. My daily driver only has 8GB of RAM.

So it makes me think: how do decade-old C/C++ compilers handle code transformation? I think there's something we can learn from them.

**Comment by L2jLiga** [comment]
@trusktr feel free to open new issue, btw issues is one of ways to improve Terser :)

**Comment by fabiosantoscode** [comment]
There's no need. I'm working on memory usage already. But it's easier said than done, and it involves a separate project. You can't really stream a javascript file into an AST, and then cross-reference variables, inline, drop dead code, and keep mutating it in multiple passes. Especially if the project is really complex and hasn't been built to do that in the first place.

**Comment by ycjcl868** [comment]
+1

**Comment by fabiosantoscode** [comment]
Due to using the new source-map package, the latest Terser version is a bit more resistant to this issue.
