### ISSUE TITLE
Cached variables can lead to incorrect toplevel trasnpilation

### ISSUE THREAD

**Issue by ma2ciek** [terser-js/terser#165]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V`)**

3.10.11

**Complete CLI command or `minify()` options used**

```js
// Terser options
{
	toplevel: true,
	mangle: true,
	nameCache: {
		vars: {
			props: {
				$add: 'foo'
			}
		},
		props: {
			props: {}
		}
	}
}
```

**`terser` input**

```js
// a.js
import { add as someAdd } from './b';

console.log( someAdd( 1, 2 ) );
```

```js
// b.js
export function add( x, y ) {
	return x + y;
}
```

**`terser` output or error**

```js
export function foo(n,r){return n+r}
import{add as o}from"./b";console.log(o(1,2));
```

**Expected result**

The original exported `add` function should stay as it is. Eventually, its name should be transformed along with all its occurrences in imports.

**Comment by ma2ciek** [comment]
I've created a repository with this bug reproducible: https://github.com/ma2ciek/terser-bug.

**Comment by kzc** [comment]
Thanks for the detailed bug report.

Initially I thought that the `nameCache` was contrived and couldn't be created through normal minification, but that's not the case:

```
$ rm -f cache.json

$ echo 'function add(){Math.random();} add(); add();' | terser --toplevel -mc --name-cache cache.json
function n(){Math.random()}n(),n();

$ cat cache.json && echo
{"vars":{"props":{"$add":"n"}}}

$ echo 'export function add(x, y){ return x + y; }' | terser --toplevel -mc --name-cache cache.json
export function n(n,r){return n+r}
```

I have a fix for this.

**Comment by kzc** [comment]
Another bug variation:
```
$ cat cache.json && echo
{"vars":{"props":{"$add":"n"}}}

$ echo 'export class add{}' | terser --toplevel -mc --name-cache cache.json
export class n{}
```
Is anyone aware of other failing scenarios?

**Comment by kzc** [comment]
A few more:
```
$ cat cache.json && echo
{"vars":{"props":{"$add":"n"}}}

$ echo 'export var add = 1;' | terser -mc --name-cache cache.json
export var n=1;

$ echo 'export let add = 1;' | terser -mc --name-cache cache.json
export let n=1;

$ echo 'export const add = 1;' | terser -mc --name-cache cache.json
export const n=1;
```
Any others?

**Comment by kzc** [comment]
Okay, I have a more general fix that should handle all export declaration scenarios.

**Comment by kzc** [comment]
@ma2ciek Please try #166 and report your findings.

**Comment by ma2ciek** [comment]
Thanks for the quick fix! It works perfectly on that branch for our needs. I've been tested it on our codebase and no error has occured after the minification.
