### ISSUE TITLE
Changelog is missing

### ISSUE THREAD

**Issue by gfx** [terser-js/terser#167]
Thanks to fixing #120, which is one of the reasons that we should use terser rather than uglify-(js|es), but I don't know other issues that are fixed in terser.

Can you maintain changelog, which should be important for a nice software?

**Comment by kzc** [comment]
This issue came up all the time in the Uglify project. Maintaining a changelog is a maintenance burden that we don't have time for. We're all volunteers here. No one is paid to work on Terser. [`git log`](https://github.com/terser-js/terser/commits/master) is this project's official change log. It has detailed descriptions of what has changed.

**Comment by gfx** [comment]
I see. Anyway, thanks for maintaining this project.

**Comment by curiousdannii** [comment]
A git log is no substitute for a changelog, especially when your git logs are sometimes very brief and explain nothing. https://github.com/terser-js/terser/commit/6be107ba3783b2ed0948899d923d79668c2517f0

But I guess as long as you tag in the log semver major and provide a migration guide next major release, that's at least leagues ahead of UglifyJS.

**Comment by kzc** [comment]
@curiousdannii Oh wonderful. You've found this project to continue your useless whining. You are owned nothing. No one cares if you use Terser. Personally I'd prefer that you didn't. People like you discourage others from working on open source software altogether.

**Comment by curiousdannii** [comment]
Polite requests for major changes to be documented are not whining. I don't want to discourage anyone from working on open source software. I do want to encourage good project management practices.

How much of a burden is it really? Maybe it can be a stretch goal for the patreon.

**Comment by kzc** [comment]
I think this minifier is better suited for you and meets your stringent requirements:

https://github.com/yui/yuicompressor/blob/master/doc/CHANGELOG

**Comment by curiousdannii** [comment]
You're a funny guy. I've registered my support for this issue, I won't keep commenting. Thanks for keeping the project maintained.
