### ISSUE TITLE
Drop Unused Imports

### ISSUE THREAD

**Issue by azizhk** [terser-js/terser#168]
**Bug report or Feature request?** Feature Request

**Complete CLI command or `minify()` options used**
```js
{
  compress: {
    side_effects: true
  },
  output: {
    beautify: true
  }
}
```

**`terser` input**
```js
import unused from "abc";
export const A = "hello"
```

**`terser` output or error**
```js
import "abc";
export const A = "hello"
```

**Expected result**
```js
export const A = "hello"
```

## Way to go about it:
Well this can be done in two ways
1. We have a global flag that all imports with variable declared be assumed as pure and removed as is.

2. Or we use the `/*#__PURE__*/` comment to determine whether an input is pure. Something like:
  ```js
  import unused from /*#__PURE__*/"abc";
  ```
Derived from the old require syntax:
```js
const unused = /*#__PURE__*/require("abc");
```

I know that this looks like part of bundler domain, but I'm hoping to not use any bundler, aiming for something like https://developers.google.com/web/fundamentals/primers/modules, https://www.sitepoint.com/using-es-modules/

**Comment by kzc** [comment]
Pure annotations are only intended to work with function calls. It already works with `/*#__PURE__*/require("package")`.

ES6 modules can be `import`ed just for their side effects.

I'd be willing to review a PR that would introduce a new top level `minify` option `pure_modules` (and `--pure-modules` in the CLI) defaulting to `false`. If set to `true` it could assume that all unreferenced ES6 modules (`import "module";`) can be dropped. This PR would have to contain tests and documentation. `pure_modules` could optionally support a regex to specify that specific ES6 module imports are pure.

**Comment by fabiosantoscode** [comment]
We can't do this. The module could have a side effect.

**Comment by fabiosantoscode** [comment]
Let the linters warn of unused variables

**Comment by Conduitry** [comment]
I think the idea is here to augment the treeshaking abilities of bundlers. The linter won't warn about unused variables, because - on a per-file basis - each variable _will_ be used, just possibly as an export.

Rollup has an option `pureExternalModules` that can be set so that it assumes merely importing external modules has no effect, but there are still cases where it would be nice if the programmer could provide extra information about what can be dropped.

That said - yes, this does indeed seem to be more the bundler's domain - and no, I'm not sure that 'I'm hoping not to use any bundler' is a valid use case.

**Comment by kzc** [comment]
This issue can be closed as a WONTFIX.

**Comment by fabiosantoscode** [comment]
Yes, sorry, we can't do this. Module bundlers can provide it.

**Comment by def14nt** [comment]
@fabiosantoscode Why a WONTFIX? Could you provide a better explanation?

**Comment by azizhk** [comment]
I understand that import statements can have side effects but we can not enable it by default.

But, as far as I can understand (and I agree) this feature is not that required as we have alternatives.
So the contributors might not find time to add this feature. (as not that incentivized).
I would suggest if you are open to a Patreon bucket to help incentivize this feature, this might get picked up?

Till that time, I am looking the code in my own free time (as I need this feature for https://github.com/ritz078/pebble/pull/141, but don't have a rigid timeline), I understand that I to remove AST_Import nodes based on whether they are used on not.
