### ISSUE TITLE
Terser logo

### ISSUE THREAD

**Issue by rogeriopvl** [terser-js/terser#170]
As you guys can see, we don't have a logo yet. We're now looking for suggestions.

Post your suggestions on this issue, and please vote with ❤️ 's on the ones you like. We'll be choosing the one with more votes to be the official Terser logo!

**Comment by rogeriopvl** [comment]
I'm starting with a first suggestion. Please bear with me, I'm not a designer 😅 
![terser_logo_1](https://user-images.githubusercontent.com/38240/48517980-039e2380-e860-11e8-8c95-d7ffcf85da76.png)

This is something simple and straight to the point.

**Comment by rogeriopvl** [comment]
Here's an improved version, now with a bit more meaning:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/38240/48723720-488ad700-ec1f-11e8-976c-3e7fa7f58a9e.png">

**Comment by rogeriopvl** [comment]
@Martii my bad. These are just random sized screenshots I'm taking from the logo. It's supposed to square format. I'll post an icon version later.

**Comment by fabiosantoscode** [comment]
Since nobody has chipped in, I picked the second one. Thanks @rogeriopvl  @Martii

**Comment by kzc** [comment]
@fabiosantoscode In the spirit of minification, can you use SVG instead of the 176 KB [logo.png](https://raw.githubusercontent.com/terser-js/terser/master/logo.png)? It would reduce the image size to around 5 KB and improve initial page load time. For comparison: Webpack's SVG logo is 647 bytes, and Preact's is 874 bytes. Github doesn't support any browser versions that cannot display SVG (like IE8), so no issue there.

**Comment by fabiosantoscode** [comment]
If @rogeriopvl used a vector program, sure!

**Comment by kzc** [comment]
There's a number of free high quality vector tracing png/jpg to svg converters. Just google for it. I tried an online version with good results.

**Comment by fabiosantoscode** [comment]
I'm happy with the PNG version. Besides, the weight is already in the .git folder

**Comment by kzc** [comment]
> Besides, the weight is already in the .git folder

What does that have to do with initial https://github.com/terser-js/terser load time?
