### ISSUE TITLE
Compress Function in Object Literal to Arrow Function but Ecma Version Is 5

### ISSUE THREAD

**Issue by StabbarN** [terser-js/terser#178]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V`)**
Tested two versions:
- terser 3.10.12
- master at this moment to include https://github.com/terser-js/terser/pull/173

**Complete CLI command or `minify()` options used**
```
node_modules/.bin/terser --compress -- test.js
```

**`terser` input**
`test.js` contains
```
const obj = {
    fn() {
        return 0
    }
}
```

**`terser` output or error**
Output: 
```
const obj={fn:()=>0};
```

**Expected result**
Functions in object literals shouldn't be compressed to an arrow function because default compress and output ecma version is 5. Setting ecma version to 5 explicitly doesn't help.

Functions in object literal is es6 ( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions ) and arrow function is also es6. However, browsers can support functions in object literal but not arrow function, which is the case of Safari iOS9.

**Comment by kzc** [comment]
Your input code is ES6:
```
$ echo 'const obj={fn(){return 0}};' | node_modules/.bin/acorn --ecma5
The keyword 'const' is reserved (1:0)
```
```
$ echo 'var obj={fn(){return 0}};' | node_modules/.bin/acorn --ecma5
Unexpected token (1:11)
```
so any ES6 to ES6 transform is fine regardless of the `ecma` setting.

**Comment by kzc** [comment]
Just so there's no confusion, Terser will not transpile ES6 code to ES5. For that you have to use Babel or some equivalent program.

The default `ecma: 5` setting is there in `compress` to avoid converting ES5 code into ES6.

**Comment by StabbarN** [comment]
Yes, I know Terser won't transpile. We use babel and browserslist for that. Babel outputs code to be run on ios9 and later. It works great. Terser, however, transforms the code to es6 features that isn't supported on ios9. Can we disable these kind of transforms or is `Terser` incompatible with @babel/preset-env and Browserslist?

**Comment by kzc** [comment]
Terser doesn't transform ES5 code to ES6 with its default minify settings. You are passing ES6 code to Terser. Contact the Babel project for help how to fix your configuration to generate ES5.

Unless you can demonstrate a genuine Terser bug, this issue can be closed.

**Comment by StabbarN** [comment]
> so any ES6 to ES6 transform is fine regardless of the ecma setting.

Ok, if that's fine this isn't a bug. It's rather a lack of adjustability.

There is a lot of options in https://github.com/terser-js/terser#compress-options. For example `arrows` disables a ES6 to ES6 transform, would you accept a well-written PR that adds another option to disable the transform `var obj={fn(){return 0}};` to `var obj={fn:()=>{return 0}};`?

**Comment by kzc** [comment]
> It's rather a lack of adjustability

Hilarious.

> `arrows` disables a ES6 to ES6 transform, would you accept a well-written PR that adds another option to disable the transform `var obj={fn(){return 0}};` to `var obj={fn:()=>{return 0}};`?

No new option is necessary. Disabling `arrows` already does exactly that:

```
$ echo 'var obj = { fn(){return 1 + 2;} };' | terser -mc
var obj={fn:()=>3};

$ echo 'var obj = { fn(){return 1 + 2;} };' | terser -mc arrows=false
var obj={fn(){return 3}};
```

Appreciate that shorthand methods in object literals are not valid ES5. It's an ES6 feature.

**Comment by StabbarN** [comment]
Sorry! Totally missed that. Thanks for your quick responses!
