### ISSUE TITLE
Why is Boolean(foo) not replaced with !!foo ?

### ISSUE THREAD

**Issue by laruiss** [terser-js/terser#182]
**Question**

Hi, I was wondering why `Boolean(foo)` was not converted to `!!foo`. Is it a choice?
The same goes with `Number(bar)`, why not convert it to `+bar` ?

terser 3.10.13

```
const terser = require('terser')

var code = "const foo = Boolean(bar)";
var result = terser.minify(code);

console.log(result)
```

**`terser` input**

`const foo = Boolean(bar)`

**`terser` output or error**

`const foo=Boolean(bar);`

**Expected result**

`const foo=!!bar`

**Comment by kzc** [comment]
```
$ echo 'console.log(Boolean(foo), Number(bar));' | terser -c unsafe
console.log(!!foo,+bar);
```

**Comment by Martii** [comment]
So if someone extends the `Boolean` object via `.prototype` it will change the behavior since it's using a `!!`  primitive on output?

**Comment by kzc** [comment]
@fabiosantoscode Half the open issues can be closed out as answered or irrelevant.

**Comment by fabiosantoscode** [comment]
I know @kzc but it's been busy. I'll try to clean up today

**Comment by def14nt** [comment]
Why was this closed? It's bad practice to extend native classes anyway.

**Comment by laruiss** [comment]
@def14nt Even though I agree with you, well... I closed it because @kzc answered my questions:
- Yes it is a choice, because you never know if developers won't change the behaviour of Boolean() and Number()
- You can still convert it as **I think** it should: with the `unsafe` option
