### ISSUE TITLE
Remove also window.console.log and global.console.log

### ISSUE THREAD

**Issue by sciamp** [terser-js/terser#187]
**Bug report**

**Version**

terser 3.11.0

**Complete CLI command or `minify()` options used**
```
terser -c drop_console=true
```

**`terser` input**
```
console.log('[console] cannot see me!');
window.console.log('[window.console] cannot see me!');
global.console.log('[global.console] cannot see me!');
```

**`terser` output or error**
```
window.console.log('[window.console] cannot see me!');
global.console.log('[global.console] cannot see me!');
```

**Expected result**
```
```

**Comment by fabiosantoscode** [comment]
Nice catch. I'll work on this one in the coming weeks.

**Comment by sciamp** [comment]
Thanks :)

I'm willing to help though, so if you can think (sorry but I didn't have any chance to take a look at the code) this is suitable for a newcomer I can try to PR a fix for this!

**Comment by fabiosantoscode** [comment]
I actually think it is! Go ahead!

**Comment by kzc** [comment]
This feature is not worth implementing as people rarely prefix console logging with the non-portable `global` or `window` and there is a simple workaround:

```
$ cat input.js 
foo();
console.log('[console] cannot see me!');
window.console.log('[window.console] cannot see me!');
global.console.log('[global.console] cannot see me!');
bar();
```
```
$ terser input.js -c drop_console,pure_funcs=[window.console.log,global.console.log]
foo(),bar();
```

**Comment by fabiosantoscode** [comment]
Not a bad workaround but I'd say still implement it

**Comment by kzc** [comment]
A few things... 

1. It's working exactly as documented:

  - `drop_console` (default: `false`) -- Pass `true` to discard calls to
  `console.*` functions. If you wish to drop a specific function call
  such as `console.info` and/or retain side effects from function arguments
  after dropping the function call then use `pure_funcs` instead.

2. There is no precedent for this in the library. Terser does not make special provisions for the global variables `window` or `global` in *any* feature - they are treated just as any other undeclared global variable. Also, properties like `window.foo` and `global.foo` are subject to `mangle.properties`, while the symbol `foo` is subject to `mangle` - they are not tied.

3. Adding rarely used features leads to a bloated and slow minifier - particularly when simple workarounds exist.

**Comment by fabiosantoscode** [comment]
Ok, I agree. @sciamp stop implementing this. Thanks, but find another issue you could contribute to, like checking the typescript PR is working properly, that would be amazing!

Bye <3

**Comment by def14nt** [comment]
@kzc Seems a bit lazy to be honest. Isn't that the point of `drop_console`?
