### ISSUE TITLE
'join_vars' puts property names with the same name in one object literal

### ISSUE THREAD

**Issue by alinnert** [terser-js/terser#193]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V`)**

3.10.11

**Complete CLI command or `minify()` options used**

~~~ js
{
  output: { comments: false },
  compress: {
    join_vars: false // <- this issue is about this option
  }
}
~~~

**`terser` input**

~~~ js
const obj = {
  foo: 'bar'
}
obj.foo = 'baz'
~~~

**`terser` output or error**

~~~ js
var o = {
  foo: 'bar',
  foo: 'baz'
}
~~~

In IE11 this throws the error: `SCRIPT1046: Multiple definitions of a property not allowed in strict mode`.

A library that produces this error is [GLightbox](https://github.com/mcstudios/glightbox) if bundled with Webpack in production mode.

Honestly, I can't say where the strict mode comes from. From the library? Or does Terser add strict mode notations?

Anyway, I'm able to avoid this error by setting the option `compress.join_vars` to `false`.

**Expected result**

That's hard to say. I don't know when exactly (i. e. in what other cases) this happens but in this very case it should be safe to remove `foo: 'bar'` completely. For other cases I don't know enough about how Terser works though. But a property should never merged into an object literal if a property with the same name already exists.

**Comment by fabiosantoscode** [comment]
Thanks for the report. Closing this as it has been fixed. Releasing soon, otherwise you can use it in master now
