### ISSUE TITLE
incorrect indent level

### ISSUE THREAD

**Issue by da0ka** [terser-js/terser#194]
sometimes output code's indent level is not correct when options.output.beautify=true and options.output.comments=true. I tested https://unpkg.com/terser@3.11.0/dist/bundle.js

**Comment by da0ka** [comment]
test code is below.
if(a);
else{
      // .
      if (a) {
          var b=0;
      }
      // .
      if (a) {
          var c=0;
      }
      // .
      if (a) {
          var d=0;
      }
}

**Comment by fabiosantoscode** [comment]
Now it does this:

```
if (a) 
   ;
else {
    if (a) {
        var b = 0;
    }
    if (a) {
        var c = 0;
    }
    if (a) {
        var d = 0;
    }
}

```

Better?
