### ISSUE TITLE
Starting a new project (but keeping terser on)

### ISSUE THREAD

**Issue by fabiosantoscode** [terser-js/terser#200]
Starting today, I'm writing a compiler that's capable of minimizing and optimizing javascript.

It operates on a very simple bytecode comprised of only functions, arithmetics, assignment, conditions, try..catch and function calls.

The idea will be to help terser do its job and also optimise javascript as much as possible.

Another nice thing I'll be doing is treat JSX elements as values, which would make it possible to store them in a const instead of creating them all over again. Another project is react-off, which will attempt to remove React from a web project, making it DOM based.

We can also turn fs.readFileSync into await fs.promises.readFile(), and all functions up to the root into async functions. This will make it easier to write code that seems synchronous and is tested as synchronous, but is actually optimised into async code (with a warning when it fails to do so).

There's a number of languages that compile to javascript, including Go, C/C++ and rust (as webassembly modules), typescript/flow and even java. I'll use these compilers to produce a utopia where you can mix together and use any language you please in a project, which yields the best results in each module.

Oh, and yes, it will understand modules.

I don't plan to implement terser's features in the compiler (I mean to use terser before outputting a prod build), but if anyone sends a PR they're welcome to.

**Comment by fabiosantoscode** [comment]
This project will be supported by the same patreon, and this does not mean I'm abandoning terser at all.

**Comment by leeoniya** [comment]
> Another project is react-off, which will attempt to remove React from a web project, making it DOM based.

seen https://github.com/sokra/rawact?

**Comment by fabiosantoscode** [comment]
@leeoniya thanks for finding that, you've just saved me a ton of work! I'm guessing I'll incorporate it into our compiler.

**Comment by fabiosantoscode** [comment]
Could you write a PR @pygy ? Just add an option to turn it on and add it to lib/index ;)
