### ISSUE TITLE
Use [].forEach instead of a for loop

### ISSUE THREAD

**Issue by fabiosantoscode** [terser-js/terser#201]
According to Paul Lewis, these are equivalent, though the forEach is a lot more readable.

What is your take @kzc? We've talked about this before. I know some engines don't optimise this, but I feel the difference is irrelevant, since you're running a production build anyway and it will take a million times more time than all the forEach loops combined.

**Comment by jhpratt** [comment]
> though the forEach is a lot more readable

Why would readability matter? Terser is _literally_ removing all readability by minifying code.

**Comment by fabiosantoscode** [comment]
I'm talking about the code in lib/ast.js. 

But, in the compressor, if we can prove something is an array, we might create a loop for it using forEach since it's shorter. I might be able to do it in jscomp.

**Comment by nifgraup** [comment]
`forEach` can be more readable but a standard `for (var i = 0; i < arr.length; i++)` is almost as readable IMO. Optimizations are best in combination with performance profiling.

Since you mentioned "prove something is an array", porting the code to TypeScript or Flow might be an idea.

**Comment by fabiosantoscode** [comment]
@nifgraup ever heard of tern.js? Its type inference is so good I created a converter from javascript to c++ with types based on it. It kind of worked.

**Comment by nifgraup** [comment]
@fabiosantoscode  I hadn't had a look at tern.js, thanks for the pointer. The documentation barely touches upon type declarations, seems like it is mostly about inferring types. It's good to get a (compilation) error when something is `AST_Node | undefined` when you assume it to be `AST_Node`.

**Comment by fabiosantoscode** [comment]
tern.js is all about giving you warnings in the editor when the type is not going to work anymore (so it doesn't disencourage duck typing), not compilation errors. But I guess you could install it in your webpack or rollup and have your compilation errors.

**Comment by fabiosantoscode** [comment]
And probably there's a CLI that exits 1 when the types don't make sense, and if there isn't, send a PR :)
