### ISSUE TITLE
commit e7f6c1eeca9ed4 breaks the bundle by leaving a stray "require"

### ISSUE THREAD

**Issue by pygy** [terser-js/terser#203]
**Bug report**

**Version 3.13.0+**

**Complete CLI command or `minify()` options used**

Any... the bundle is broken in non-CommonJS environments by the presence of a stray `require()` call. Terser is thus not populated (`Terser.minify` is not a function).

[Example that works](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8YWACcyAB3gACMKNgBeHPAlhUAenUBXOhIDWAcww9c6xKMiiAAgGYMARgBMGAAzqkZMPHUAjHUhgMACswAD5BdRFxKVCAHTphMUl4OLoeOjBuQKhuAwAKABUIC2KMXDI6MhIATzzYrl4vaQZpBWkAVnqASi74iKjk0M5IGAQyRtYbVABOEABfAF05oA) with v3.12.0.

[Example that fails](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8YWACcyAB3gACMKNgBeHPAlhUAenUBXOhIDWAcww9c6xKMiiAAgGYMARjsAGdUjJh46gEY6kMDABWYAB8guoi4lLBADp0wmKS8DF0PHRg3P5Q3AYAFAAqEBaFGLhkdGQkAJ450Vy8HtIM0grSAKy1AJQdsWERicGckDAIZPWsTqgALDYgAL4AurNAA) with v3.13.0 (same bug with 3.13.1).

Possible solutions:

- inline the domprops in the source code
- use a bundler to resolve dependencies
- hack something in package.json to store `domprops.json` in a top-level variable at build time?

**Comment by fabiosantoscode** [comment]
Thanks for catching this. I'm pushing a fix and will release later.

**Comment by pygy** [comment]
You'll probably want to turn the JSON file into an UMD-ish JS file:

```
var domprops = []
if (typeof module != undefined) module.exports = domprops;
```
Then if can be either required or inlined in the build script.

**Comment by fabiosantoscode** [comment]
No, it works OK with just var domprops =
