### ISSUE TITLE
Can I safely use terser as the alternative solution uglify-js(v3) for es3/5, in any case?

### ISSUE THREAD

**Issue by LongTengDao** [terser-js/terser#205]
**Bug report or Feature request?**

Question.

Does `terser` have some defects that `uglify-js` does not have?

Since the API of `terser` is compatible with `uglify-js` (v3) and there is more support for es6.

**Comment by avdg** [comment]
Terser started as a fork from uglifyjs, so just give it a try. Most changes are related to implementing features from es 6 / es 2015 or later

There might be some issues solved in uglifyjs differently than in terser. But by the time of the fork, uglifyjs was already quite stable and was already used in a large amount of projects.

**Comment by LongTengDao** [comment]
@avdg thank you!

---

If there is nothing else, closing the issue is acceptable. I'll just wait for a while.
