### ISSUE TITLE
minify options.compress.computed_props should treat property name "__proto__" differently.

### ISSUE THREAD

**Issue by LongTengDao** [terser-js/terser#206]
**Bug report or Feature request?**

Bug report.

**Version (complete output of `terser -V`)**

3.13.1

**Complete CLI command or `minify()` options used**

```json
{
    "compress": {
        "computed_props": true
    }
}
```

**`terser` input**

```js
throw { ["__proto__"]: 1, ["name"]: 2 };
```

**`terser` output or error**

```js
throw{__proto__:1,name:2};
```

**Expected result**

```js
throw{["__proto__"]:1,name:2};
```

>   `computed_props` (default: `true`) -- Transforms constant computed properties into regular ones: `{["computed"]: 1}` is converted to `{computed: 1}`.

The `__proto__` (or written like `"__proto__"` or `'__proto__'`) property is very different with all other properties, it will set the proto of the object to it's value.

But when use `["__proto__"]`, it will be a normal property.

**Comment by fabiosantoscode** [comment]
This is an old issue. Fixed it now. Will release soon!

**Comment by LongTengDao** [comment]
> This is an old issue. Fixed it now. Will release soon!

Oh, thank you!

How does it work, just treat `__proto__` differently like I said above, or with other rules?

**Comment by fabiosantoscode** [comment]
Yeah, a simple check to see if the constant string value is '__proto__'
