### ISSUE TITLE
Is it still necessary to support legacy Node.js?

### ISSUE THREAD

**Issue by Connormiha** [terser-js/terser#207]
Current Terser supports nodejs `0.8.0`, `0.10.0`, `0.12.0`. I think in 2019 supporting of legacy node.js does not give any advantages.
Developers migrated from UglifyJS to Terser because Terser supports ES2015+.
I can't  believe that developer who use modern ECMAscript + Terser runs it with legacy Node(without es6 support).
Popular `node.js` projects are supported from Node 4 or even Node 6. For example Webpack, Jest, Karma, TypeScript have already droped support `0.12.0`.
Some parts of the code can be improved without support legacy Node.

**Comment by fabiosantoscode** [comment]
It's not hard to support those versions, as long as we keep the code ES5.

A nice improvement would be to use babel or ecmacomp (when it's done) on the source and convert it to ES5 code that runs on 0.10.

I don't think we need to support 0.* forever, but this 0.8 support you're talking about is new to me. Maybe it's just because we support 0.10 it ends up working on 0.8

Happy holidays!

**Comment by avdg** [comment]
From my perspective it was nice to "support" these old versions as these v8 compilers did not include es5. It's a nice indicator if something was implemented too futuristic.

But given that this branch is already kinda es6 native and that just supporting es5 is something of the past, maybe that we can support a more recent old version of v8.

I just don't want a minifier to support only the latest version as that will break the flexibility with compatibility and increase the possibility of unforseen bugs, especially with browsers lagging implementation or being out of date.

**Comment by nifgraup** [comment]
Turns out rollup needs at least node.js 6, https://travis-ci.org/terser-js/terser/builds/474008895?utm_source=github_status&utm_medium=notification.

Should we raise the minimum version to 6 or have different build and runtime requirements?

**Comment by fabiosantoscode** [comment]
How about parcel? Or an older version of rollup. If needed we can go with webpack even. It's not as small but we're not trying to be small.

**Comment by nifgraup** [comment]
Parcel requires node 6 https://github.com/parcel-bundler/parcel/blob/master/package.json#L29, webpack as well https://github.com/webpack/webpack/blob/master/package.json#L86.

It's not sensible to use an older version of rollup, we have to be able to upgrade if bugs arise. In fact I discovered a bug in rollup that caused a terser unit test to fail, now fixed: https://github.com/rollup/rollup/pull/2607

You didn't address if 6 is too new or what you think of having to a different minimum node.js version requirements to run and build terser. Node.js v4 had EOL in April last year https://github.com/nodejs/Release#end-of-life-releases.
