### ISSUE TITLE
Properties of outside variables are wrongly mangled

### ISSUE THREAD

**Issue by Mann90** [terser-js/terser#219]
**Bug report or Feature request?**

Bug report.

**Version (complete output of `terser -V`)**
terser 3.14.0

**Complete CLI command or `minify()` options used**
`terser --compress --mangle --mangle-props -- test.js`

**`terser` input**

The content of a simple test.js is:
`GameController.graphicsManager.setUp({size: 100});`. GameController is a class from an external library.

**`terser` output or error**
GameController.o.l({size:100});

**Expected result**
`GameController.graphicsManager.setUp({size: 100});` 
Since GameController is a class from an external library, the properties of external variables/clases should NOT be changed.

**Comment by fabiosantoscode** [comment]
Thanks for this report. I'll have a look. Can you avoid the bug by adding a mangle regexp that doesn't mangle that property specifically?

**Comment by fabiosantoscode** [comment]
A quick look at uglifyJS's git repo shows me that this has never worked.

**Comment by fabiosantoscode** [comment]
Released as `v3.14.1`
