### ISSUE TITLE
Stable naming algorithm

### ISSUE THREAD

**Issue by ForsakenHarmony** [terser-js/terser#220]
**Bug report or Feature request?**

A bit of both

**Version (complete output of `terser -V`)**

`rollup-plugin-terser: 3.0.0`

**Complete CLI command or `minify()` options used**

https://github.com/developit/microbundle/blob/master/src/index.js#L430

**`terser` output or error**

For microbundle we have size snapshots to see if they change due to a change in the code, because we try to get the smallest (correct) output possible

https://travis-ci.org/developit/microbundle/builds/474470384#L597

The thing that confuses me is that the names seem to randomly change, just wondering if you could have an algorithm that gives a "predictable" output

**Comment by fabiosantoscode** [comment]
If the input doesn't change, then the names shouldn't change either. The names are based on the strings that are around them. If this is actually totally random even if the file doesn't change, let me know so I can reopen the issue. Thanks!
