### ISSUE TITLE
babel-loader with regex property on mangle doesn't work correctly

### ISSUE THREAD

**Issue by cs09g** [terser-js/terser#237]
**Bug report or Feature request?**
It looks a bug.

**Version (complete output of `terser -V`)**
latest I guess. it's used by `terser-webpack-plugin` v1.2.1.

**Complete CLI command or `minify()` options used**
```javascript
// webpack.config.js
  ...
  module: {
    rules: [{
      exclude: /node_modules/,
      use: {
        loader: "babel-loader",
      },
    }],
  },
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          mangle: {
            properties: {
              regex: /^_/,
            },
          },
        },
      }),
    ],
  },
  ...
```

**`terser` input**

**`terser` output or error**
![image](https://user-images.githubusercontent.com/7428017/51020625-760e5400-15c2-11e9-8d42-6b484c20661e.png)
`_setupAndExtendOptions` is mangled to `this.M`, but `key: '_setupAndExtendOptions',` is not mangled as `M` so it throws `TypeError: this.M is not a function`

**Expected result**
when `mangle` is set, the codes should be mangled both on declaration and usage part.

Sorry about mixing up with `terser-webpack-plugin` though, I'm not sure if it is an issue on `terser` or issue on compatibility with babel-loader.
also reported on terser-webpack-plugin: [issues/55](https://github.com/webpack-contrib/terser-webpack-plugin/issues/55)

**Comment by fabiosantoscode** [comment]
We really have no way to know what the babel machinery (or any machinery) is doing to create objects and what it uses to get object keys, so we can't fix it, sadly.

It's for stuff like this that there's a warning not to use mangle-props. I suggest you let it go, the code is plenty small without it.
