### ISSUE TITLE
Bug: Return statement is mixed with previous statement if such statement assigns to a class variable

### ISSUE THREAD

**Issue by bustawin** [terser-js/terser#240]
Version: 3.14.1
CLI: `terser file.js -c`
Input:
```javascript
function foo () {
  class Foo {

  }

  Foo.bar = true
  return {
    foo: Foo
  }
}

foo()
```
Output:
```javascript
function foo(){class Foo{}return Foo.bar=!0,{foo:Foo}}foo();
```
Return should not bee returning `Foo.bar = !0` but only `{foo: Foo...}`:
```javascript
function foo(){class Foo{}; Foo.bar=!0; return {foo:Foo}}foo();
```
Adding another statement (`const x = 1`) between `Foo.bar = false` and the `return` fixes this problem, so maybe the bug is not only for class variable assignments but it definitely is not generic to anything.

PS: Let me take the chance and thank you for this amazing software :-)

**Comment by fabiosantoscode** [comment]
This is a consequence of the `sequences` option. You might have noticed the code works just the same. It's just something we do to save bytes, join stuff with the comma operator. `return foo?(alert("ok"),0:1` is a lot smaller than the corresponding if and return.

**Comment by fabiosantoscode** [comment]
If you don't like it, disable the sequences compress option
