### ISSUE TITLE
Mangling issue with AngularJS1

### ISSUE THREAD

**Issue by jandolezal71** [terser-js/terser#242]
Hi,

I am migrating from browserify to webpack on my AngularJS project. Everything works fine on development mode, but wrong on production one.

```
webpack: 4.28.4
angular: 1.5.11
```

I am using dependency injection and I am specifically writing '$inject'.

```
Service.$inject = [ 'service1', 'service2' ];
angular.module('app', Service);
```
In production mode console will fill up with errors: `Unknown provider: eProvider <- e <- Modal`.

I tried to switch mangle off and its working properly, but then package size is huge :(

This works: 
```
new plugins.TerserMinifier({
  terserOptions: {
    mangle: false,
  },
});
```

This not:
```
new plugins.TerserMinifier({
  terserOptions: {
    mangle: {},
  },
});
```

I tried to put some keywords as some topics said, but it didn't work.
```
new plugins.TerserMinifier({
  terserOptions: {
    mangle: {
      keep_fnames: true,
      keep_classnames: true,
      reserved: [ 'angular', '$' ]
    },
  },
});
```

Code without mangle looks like this:
```
directive_DropdownTriggerDirective.$inject = ["$scope", "$element"];
Object(registry["a" /* register */])('sklik.shared', directive_DropdownTriggerDirective);
```
Second thing, i noticed a bigger amount of `/* unused harmony export ... */` comments in dev code, but these modules ARE definitely used.

What could i do?

Thank you.

**Comment by jandolezal71** [comment]
This was our issue with $inject plugin afterall :(

**Comment by funkybob** [comment]
Having just run into this same error message, @jandolezal71 could you please elaborate on how the $inject plugin was an issue, and how you resolved it?
