### ISSUE TITLE
Broken patreon link

### ISSUE THREAD

**Issue by GrosSacASac** [terser-js/terser#243]
To fix replace https://www.patreon.com/terser_jscomp_maintainer
with https://www.patreon.com/terser_ecmacomp_maintainer
in the readme

**Comment by GrosSacASac** [comment]
(only in npm readme)

**Comment by bdrtsk** [comment]
Is there a home address of this person? I want to thank him personally for breaking the web

https://twitter.com/swyx/status/1091959223406084096

![screenshot from 2019-02-04 12-07-50](https://user-images.githubusercontent.com/45076741/52202497-437d1180-2877-11e9-99fa-62f61db7894a.png)
