### ISSUE TITLE
Identifiers for built-in objects are retained with pure_getters

### ISSUE THREAD

**Issue by filipesilva** [terser-js/terser#245]
Note: this is the exact same issue as https://github.com/mishoo/UglifyJS2/issues/3317. I'm reporting it in both places because I am not sure what the policy is for porting fixes from UglifyJS to Terser. If it is enough to be reported there, please close this one.

**Bug report or Feature request?**

I think this is a bug, but it might be working as intended.

**Version (complete output of `terser -V`)**
3.14.1

**Complete CLI command or `minify()` options used**

`terser test.js --toplevel --compress pure_getters --mangle`

```js
// test.js
var isArray = Array.isArray;
```

**`terser` output or error**
Output is `Array;`. 

**Expected result**
I expected the output to be nothing. 

Maybe there's a reason for leaving `Array` there that I don't see.

**Comment by filipesilva** [comment]
Something similar happens with the following sample as well:
```
var __window = typeof window !== 'undefined' && window;
```

It gets minified to:
```
"undefined"!=typeof window&&window;
```

Under the same assumptions as above, I expected it to be minified to nothing.

**Comment by fabiosantoscode** [comment]
Nice catch and examples. I'll have a look now.

**Comment by fabiosantoscode** [comment]
Published as v3.16.0

**Comment by fabiosantoscode** [comment]
Thanks for the issue

**Comment by fabiosantoscode** [comment]
What stays around in this case?

**Comment by filipesilva** [comment]
Sorry, I had a broken link in the comment above. https://github.com/terser-js/terser/issues/250 is the right issue.

For input
```
var __window = typeof window !== 'undefined' && window;
```
the output is
```
"undefined"!=typeof window&&window,
```

I have a few more examples in https://github.com/terser-js/terser/issues/250.
