### ISSUE TITLE
Enhancement: `new Array(5)` can be mangled into `[,,,,,]`

### ISSUE THREAD

**Issue by Alhadis** [terser-js/terser#246]
As indicated by the title, an `Array` constructor with a non-variable initial length can be more concisely written as a literal with blank elements:

~~~js
new Array(0)
[]
new Array(1)
[,]
new Array(2)
[,,]
new Array(3)
[,,,]

…

new Array(9)
[,,,,,,,,,]
new Array(10)
[,,,,,,,,,,]
~~~

The limit for this optimisation is 11, where both forms are of equal length:

~~~js
new Array(11)
[,,,,,,,,,,,]
~~~

As of v3.14.1, Terser isn't doing this, but it probably should.

**Comment by fabiosantoscode** [comment]
The Array constructor doesn't get called as often as to make this very worthwhile.

I'm not looking into this but will accept a PR.

**Comment by Alhadis** [comment]
`sed` it is then!
