### ISSUE TITLE
ERROR while ng build --prod

### ISSUE THREAD

**Issue by Shmasya** [terser-js/terser#253]
ERROR while ng build --prod

**Comment by rawzone** [comment]
@AlexKondov can confirm that also fixed my production compilation in a Laravel project using yarn / laravel-mix to compile my assets.

**Comment by bjornharvold** [comment]
Yes, downgrading to Terser 3.14.1 fixed the issue.

**Comment by CodeCrusha** [comment]
Same issue here with ng build --prod. "TypeError: Cannot read property 'minify' of undefined" in terser-wepback-plugin

**Comment by fabiosantoscode** [comment]
Fixed in 3.16.1. Will add test so it doesn't happen again. Thanks for the issue!
