### ISSUE TITLE
Add "files" option

### ISSUE THREAD

**Issue by ca0v** [terser-js/terser#257]
**Feature request**

**Version (complete output of `terser -V`)**
3.14.1

**Complete CLI command or `minify()` options used**

{
                files: ["f1.js", "f2.js"]
}

So instead of `terser f1.js f2.js` we can use `terser --config-file cf.json`

**Comment by fabiosantoscode** [comment]
Nice suggestion.

I think if we're going this way we might as well allow the input of any option in there!

Anyone willing to send a PR?
