### ISSUE TITLE
[Feature] Improved variable joining

### ISSUE THREAD

**Issue by benmccann** [terser-js/terser#260]
**Feature request**

I would like to suggest a feature that rewrites variable declarations for improved variable joining.

Consider the function below:
```
function lookup(table, key, value) {
	var lo = 0;
	var hi = table.length - 1;

	while (lo >= 0 && lo <= hi) {
		var mid = (lo + hi) >> 1;
		var i0 = table[mid - 1] || null;
		var i1 = table[mid];

		if (!i0) {
			// given value is outside table (before first item)
			return {lo: null, hi: i1};
		} else if (i1[key] < value) {
			lo = mid + 1;
		} else if (i0[key] > value) {
			hi = mid - 1;
		} else {
			return {lo: i0, hi: i1};
		}
	}

	// given value is outside table (after last item)
	return {lo: i1, hi: null};
}
```

We instead wrote it to declare `mid, i0, i1` at the top of the function near the other variable declarations for improved variable joining (`join_vars` option):
```
function lookup(table, key, value) {
	var lo = 0;
	var hi = table.length - 1;
	var mid, i0, i1;

	while (lo >= 0 && lo <= hi) {
		mid = (lo + hi) >> 1;
		i0 = table[mid - 1] || null;
		i1 = table[mid];

		if (!i0) {
			// given value is outside table (before first item)
			return {lo: null, hi: i1};
		} else if (i1[key] < value) {
			lo = mid + 1;
		} else if (i0[key] > value) {
			hi = mid - 1;
		} else {
			return {lo: i0, hi: i1};
		}
	}

	// given value is outside table (after last item)
	return {lo: i1, hi: null};
}
```

Our project enforces this coding style to get better minimized output, but it makes the code less readable and wastes time in code reviews, etc. It would be nice if terser could do this for us, so that we could take greater advantage of the variable joining feature without having to write our code differently

**Comment by fabiosantoscode** [comment]
There's an option that does something like what you're talking about:

> hoist_vars (default: false) -- hoist var declarations (this is false by default because it seems to increase the size of the output in general)

I wouldn't want this implemented on Terser as it's a low-return optimisation for the amount of complexity it would add. Have a gander at lib/compress/index.js and tell me if that's not complex enough ;)

**Comment by benmccann** [comment]
Thanks for the pointer. I'm very surprised that `hoist_vars` increases the size in general. I just tested on my project and it did increase the size there as well. Is it doing exactly when I'm describing or something else? 

When I do it manually it seems to decrease the size. Is it getting applied before variable joining and other operations?
