### ISSUE TITLE
missed optimization: function property unpacked to a variable

### ISSUE THREAD

**Issue by LiraNuna** [terser-js/terser#265]
It seems like there's a missed optimization when unpacking a function out of an object - it is assigned to a variable (`const`, `var` or `let` depending on the visibility of the object). It is a missed optimization as that assignment is adding 5 bytes to the output. 

**Bug report or Feature request?**

Feature request (missed optimization)

**Version (complete output of `terser -V`)**

```terser 3.16.1```

**Complete CLI command or `minify()` options used**

```javascript
{
  toplevel: true
}
```

**`terser` input**

```javascript
const x = {
    add: function test(x) {
        return x + x;
    },
};

console.log(x.add('A'));
console.log(x.add('B'));
```

**`terser` output or error**

```javascript
const o=function(o){return o+o};console.log(o("A")),console.log(o("B"));
```

**Expected result**
```javascript
function o(o){return o+o}console.log(o("A")),console.log(o("B"));
```

**Comment by fabiosantoscode** [comment]
That might break code. Consider this:

```
const x = {
    add: function test() {
        return foo;
    },
};
console.log(x.add())
const foo = 10
```

This code gets a `ReferenceError`. If we were to change `const o=function...` into `function o...`, then that wouldn't cause an error. function declarations are always hoisted up to the top of the wrapping function or module.

We could only do this safely if the function is already at the top, or we check what names are being used in the function before doing this.

Plus, gzip will optimize several different "const" words together through the compression algorithm, such that it's actually smaller to have a bunch of constants, than to have one less constant and one more function. Terser is derived from UglifyJS, which uses gzip to its advantage quite well.
