### ISSUE TITLE
bug: Uncaught SyntaxError: Invalid regular expression: missing /

### ISSUE THREAD

**Issue by yi-ge** [terser-js/terser#275]
terser v3.16.1:

In`Mac OS`, use npm install terser v3.16.1,

```
cat node_modules/terser/dist/bundle.min.js
```

The file ends in `59-\u0A5C\u0A5E\u0A`.

Error: `Uncaught SyntaxError: Invalid regular expression: missing /`.

**Comment by L2jLiga** [comment]
Could you provide little bit more info? node and npm versions?

**Comment by yi-ge** [comment]
Missing part of the file. `node` v11.10.0， `npm` v6.7.0。

**Comment by L2jLiga** [comment]
Could you check your `package-lock.json` file? It should contain same part:
```
    "terser": {
      "version": "3.16.1",
      "resolved": "https://registry.npmjs.org/terser/-/terser-3.16.1.tgz",
      "integrity": "sha512-JDJjgleBROeek2iBcSNzOHLKsB/MdDf+E/BOAJ0Tk9r7p9/fVobfv7LMJ/g/k3v9SXdmjZnIlFd5nfn/Rt0Xow==",
```

Also you can try to remove `node_modules` and `package-lock.json` files and run `npm install` or `npm cache verify` first

**Comment by yi-ge** [comment]
```
terser@^3.16.1:
  version "3.16.1"
  resolved "https://registry.yarnpkg.com/terser/-/terser-3.16.1.tgz#5b0dd4fa1ffd0b0b43c2493b2c364fd179160493"
  integrity sha512-JDJjgleBROeek2iBcSNzOHLKsB/MdDf+E/BOAJ0Tk9r7p9/fVobfv7LMJ/g/k3v9SXdmjZnIlFd5nfn/Rt0Xow==
  dependencies:
    commander "~2.17.1"
    source-map "~0.6.1"
    source-map-support "~0.5.9"
```

Maybe it is happens only on `yarn`? 😄

Thank you.
