### ISSUE TITLE
Don't mangle reserved for toplevel only

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [terser-js/terser#282]
**Bug report or Feature request?**

Feature-request

**Version (complete output of `terser -V`)**

3.16.1

Use case: Twemoji. 

The option "reserved" for not mangling toplevel is nice but twemoji has a peculiar code and tersering the code doesn't mangle the "twemoji" inside the function, which can be mangled. 

In other words I want to keep the name twemoji but remove the occurrences of the name inside the function and options right now don't allow it.

**Comment by fabiosantoscode** [comment]
It looks like everything is working:

```
function foo () {      
    function foobar() {
        return 5       
    }                  
    x(foobar)          
}                      
```

```
:!./bin/uglifyjs -m reserved='["foobar"]' --toplevel bug.js                                                            
function n(){function foobar(){return 5}x(foobar)}
```

Or do you want do do something like this?

```
function twemoji() {
  var twemojiFn = twemoji
  // use twemojiFn instead of twemoji
}
```

This way `twemojiFn` is mangled but not the function name.

**Comment by vijayaraghavanramanan** [comment]
Yeah, could do it but since Twemoji, the Twitter library is released frequently, the process of modifying involves more work. The code looks like: 

```javascript
var twemoji = (function (
  /*! Copyright Twitter Inc. and other contributors. Licensed under MIT *//*
    https://github.com/twitter/twemoji/blob/gh-pages/LICENSE
  */

  // WARNING:   this file is generated automatically via
  //            `node twemoji-generator.js`
  //            please update its `createTwemoji` function
  //            at the bottom of the same file instead.

) {
  'use strict';

  /*jshint maxparams:4 */

  var
    // the exported module object
    twemoji = {

**Comment by fabiosantoscode** [comment]
Well, if "twemoji" is not your own code there isn't much you can do. The only way would be to add that variable and start using it.

I'm not happy to increase the complexity of terser for such a tiny corner case. Sorry but I have to close.
