### ISSUE TITLE
Possibly wrong "instanceof" test?

### ISSUE THREAD

**Issue by vladimiry** [terser-js/terser#285]
https://github.com/terser-js/terser/blob/0cf9167c5278986744d6584255e153dd5555fd1a/lib/compress.js#L3992

So `this.parent_scope` first gets conveted to boolean and only then `instanceof` test takes place.

**Comment by fabiosantoscode** [comment]
Hey there! Thanks for the issue. Looks like @L2jLiga has fixed it in a PR so we just have to wait until conflicts are fixed!

**Comment by vladimiry** [comment]
This is taken care of and about to be merged, so closing, thanks.
