### ISSUE TITLE
Terser depends on deprecated istanbul

### ISSUE THREAD

**Issue by L2jLiga** [terser-js/terser#289]
**Bug report or Feature request?**

Not sure. Actually I don't see any usages of istanbul in Terser except of two scripts which are not included in CI build

**Complete CLI commands used**

```
git clone https://github.com/terser-js/terser.git
cd terser
npm install
```

**`terser` output or error**

```
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
```

**Expected result**
No warnings

**Comment by fabiosantoscode** [comment]
We stopped using istanbul for some reason, probably some bug. I think we can drop it entirely.

**Comment by tchetwin** [comment]
This commit https://github.com/terser-js/terser/commit/e0fdd48b0ba2eaad21ab4005c1722769e07c3fba appears to clobber PR #299.

Cloning (just now) and running tests fails, as the `istanbul` dependency is gone but the `test` script attempts to call it.

**Comment by L2jLiga** [comment]
In PR https://github.com/terser-js/terser/pull/288 scripts were updated and if it was merged it can fix build
