### ISSUE TITLE
Compression function inlining / flattening does not always produce working code

### ISSUE THREAD

**Issue by j-verse** [terser-js/terser#292]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V`)**
terser 3.16.1

**Complete CLI command or `minify()` options used**
`terser test.js -c --toplevel`

**`terser` input**
`test.js` contains the following code:
```
var g1 = ['a'];

function problem(arg1) {
  return g1.indexOf(arg1);
}

function unused(arg1) {
  return problem(arg1);
}

function B(problem) {
  return g1[problem];
}

function A(arg1) {
  return problem(arg1);
}

function main(arg1) {
  return B(A(arg1));
}

console.log(main('a'));
```

This code has no useful functionality, it's just a very stripped down piece of code that still produces the issue I'm having with my actual code.

**`terser` output or error**
Terser output:
`var g1=["a"];function problem(arg1){return g1.indexOf(arg1)}console.log(function(arg1){return problem=function(arg1){return problem(arg1)}(arg1),g1[problem];var problem}("a"));`

Running this code will lead to the following error:
`TypeError: problem is not a function`

Compression does not seem to take into account an argument overriding a toplevel function when inlining / flattening.

**Expected result**
This code should do the same as:
`console.log("a");`

What the exact proper output should be, is hard to say. If you can already change names during compression, this output could work:
`var g1=["a"];function problem(arg1){return g1.indexOf(arg1)}console.log(function(arg1){return noproblem=function(arg1){return problem(arg1)}(arg1),g1[noproblem];var noproblem}("a"));`

But if renaming is not an option, then probably skip the inlining like so:
`var g1=["a"];function problem(arg1){return g1.indexOf(arg1)}console.log(function(arg1){return function(problem){return g1[problem];}(function(arg1){return problem(arg1)}(arg1));}("a"));`

**Comment by otakustay** [comment]
My fault, failed to merge this fix to master, `2.1.2` should fix
