### ISSUE TITLE
Use ES6 Map instead of Dictionary

### ISSUE THREAD

**Issue by fabiosantoscode** [terser-js/terser#295]
**Bug report or Feature request?** feature request

**Version (complete output of `terser -V`)** N/A

**Complete CLI command or `minify()` options used** N/A

**`terser` input**

N/A

**`terser` output or error**

N/A

**Expected result**

N/A

----

There's a speed boost to be gained by using a real ES6 Map instead of a Dictionary, as it will be implemented by the underlying JS engine.

**Comment by MattiasBuelens** [comment]
I can have a go at this if you want. Seems like the logical next step after #276. 😃
