### ISSUE TITLE
domprops.js export messing with node

### ISSUE THREAD

**Issue by syranide** [terser-js/terser#296]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V`)**
v3.16.1

**Description**
Neither node v8.15 or v10.15 is able to require `terser/tools/domprops.js` now without throwing the error below, this worked just fine before the commit https://github.com/terser-js/terser/commit/e6e43800dc1de82ff58e9dd77aad349319e0aa03.

```
$ node
> require('terser/tools/domprops.js')
```
```
/.../node_modules/terser/tools/domprops.js:1
(function (exports, require, module, __filename, __dirname) { export var domprops = [
                                                              ^^^^^^

SyntaxError: Unexpected token export
```

Where the function-wrapper comes from I have no idea, it's not in the file, but I'm assuming it's a node quirk. I've tested this on two different VMs, one with node v8 from the official debian apt and one with node v10 from nodesource.

This is caused by the commit https://github.com/terser-js/terser/commit/e6e43800dc1de82ff58e9dd77aad349319e0aa03, it changes `var domprops = ...` to `export var domprops = ...`.

**Comment by L2jLiga** [comment]
Nothing wrong, it won't work without `--experimental-modules` at least. Since https://github.com/terser-js/terser/pull/209 Terser uses ECMAScript Modules for sources and rollup for bundling.

**Comment by L2jLiga** [comment]
Another possible solution is to use [esm](https://medium.com/web-on-the-edge/tomorrows-es-modules-today-c53d29ac448c)

**Comment by syranide** [comment]
@L2jLiga Hmm ok, I'm using terser as part of webpack. As I'm currently using the `webpack` (cli) command I'm unable to inject node-arguments. So as far as I understand it, this makes it incompatible with webpack-cli? (if I want to use `domprops.js`).

Maybe there's more to it, but that seems like an oversight to me. As it's only the optional `domprops.js` that is affected, would it be possible provide a backwards-compatible file until modules support is commonly available in node?

**Comment by fabiosantoscode** [comment]
The function wrapper is from node itself. It's used to provide the variables you can see in the function arguments and a closure for the module to run safely in.

Terser's internal modules aren't part of the public interface, so I'm not worried about this.

`domprops` is for mangle-props, but if you're trying to mangle properties except for DOM properties, you can pass `domprops=true` as an option.

**Comment by robert-gogolan** [comment]
I have the same issue

`terserOptions: {
   mangle: {
     properties: {
       keep_quoted: true
       reserved: require('terser/tools/domprops').domprops
       }
     }
 }`

'domprops' is not a supported options whereever i put it either in mangle or in mangle.properties.
Any ideea how to pass the --experimental-modules?
I am building the project with plain "webpack" cli command.

**Comment by syranide** [comment]
Yeah, the `domprops` option seems to only be available for terser cli. However it seems `domprops` is included by default nowadays whether you like it or not (at least for terser-webpack-plugin) as it actually behaves correctly even when I removed it, and `reserved` actually adds to the list of the default domprops now (rather than clear it). My config is a few years old so this uglify/terser-behavior must have changed somewhere along the way, because this certainly was not the behavior when I started.

Anyway, from my perspective this is actually a non-issue then unless I'm mistaken.
@robert-gogolan if you just remove the `reserved`-property it should work for you too.

**Comment by L2jLiga** [comment]
@robert-gogolan Terser should include domprops to reserved list by default, why do you need it?

According to your question with passing properties in webpack, you can try [esm](https://www.npmjs.com/package/esm) package and then use command: `node -r esm node_modules\webpack\bin\webpack.js`

**webpack.config.js**:
```javascript
import { domprops } from 'terser/tools/domprops';

// .....
terserOptions: {
    mangle: {
        properties: {
            keep_quoted: true,
            reserved: domprops,
        }
    }
}
// ....
```

**Comment by robert-gogolan** [comment]
It is activated by default, but when i activate "keep_quoted" then it minifies the domprops :(

My hacks would be to:
- c/p the domprops content in my project
- delete the export in the terser/tools/domprops
- install uglifyjs and use that from there since it just contains the array

All three kind of stinks.

I will try the esm package, thanks for the tip.

**Comment by syranide** [comment]
@robert-gogolan That's weird, I have `keep_quoted: true` too, and I'm not seeing any issues with mangling of domprops.

**Comment by robert-gogolan** [comment]
Works now.
I don't know what settings I had friday, because I tested a lot of different options configurations, so I may had screwed something up.
Now i have only mange.properties.keep_quoted and the domprops are not getting minified, which is awesome.

**Comment by syranide** [comment]
I'll go ahead and close this then as this was just caused by legacy configurations and is not actually a problem in terser.

Thanks @fabiosantoscode and @L2jLiga
