### ISSUE TITLE
how to convert 'let' to 'var'

### ISSUE THREAD

**Issue by Ycsm2015** [terser-js/terser#297]

**Comment by bschlenk** [comment]
This seems out of scope for terser. `let` and `var` are both the same length, so no minification would actually happen here. Not to mention `let` and `var` are semantically different, so making the change could affect the behavior of the program. You can use [babel](https://github.com/babel/babel) to do this sort of conversion.

**Comment by fabiosantoscode** [comment]
Closing since it's been answered
