### ISSUE TITLE
Unused tagged template literal emitting unnamed function

### ISSUE THREAD

**Issue by jondlm** [terser-js/terser#311]
Type: **Bug report**
Version: **terser 3.17.0** (also noticed the bug on 3.16.1)

Here is [a codesandbox](https://codesandbox.io/s/k788wnxqr?fontsize=14&view=editor) with a repro
```javascript
const terser = require("terser"); // 3.17.0
const inputCode = `
(function() {
  function tpl(str) {
    return str;
  }

  const unused = tpl\`test\`;
})();
`;

console.log("Invalid output", terser.minify(inputCode, { compress: true }));
// !function(){function(n){return n}`test`}();

console.log("Valid output", terser.minify(inputCode, { compress: false }));
// (function(){function n(n){return n}const t=n`test`})();
```

`compress: true` is causing terser to emitting invalid code that includes [an unnamed function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unnamed_function_statement).

**Comment by fabiosantoscode** [comment]
Looks like the code is almost correct. All it needs is some parentheses!

```
> (function(n){return n})`test`
[ 'test' ]
```

The solution to this should be to fix the PARENS code in lib/output.js

**Comment by jondlm** [comment]
I'll take a look at the code and see if I can fix it when I get some extra time in my schedule.
