### ISSUE TITLE
new Array incorrectly minified when not passed a number

### ISSUE THREAD

**Issue by Conduitry** [terser-js/terser#312]
The new feature #246/#255 in version 3.17.0 does not produce correct output when given an array constructor that is passed one argument and that argument is not a number.

**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V`)**

terser 3.17.0

**Complete CLI command or `minify()` options used**

```javascript
terser -c unsafe test.js
```

**`terser` input**

```javascript
console.log(new Array(a));
```

**`terser` output or error**

```javasrcript
console.log([]);
```

**Expected result**

```javascript
console.log(Array(a));
```

**Comment by Conduitry** [comment]
I assume that the code [here](https://github.com/terser-js/terser/blob/d01eb6f6712e013a652aaf5a09177a018f7ac200/lib/compress/index.js#L5322) should also be bailing when `args[0]` is not a literal.

**Comment by Conduitry** [comment]
There seem to be several issues here. `new Array("foo")` also minifies incorrectly. These optimizations are also only happening with `new Array(...)` and not `Array(...)`. Perhaps #255 should be reverted for now?

**Comment by Alhadis** [comment]
Is there seriously no way of checking the argument's object type in [this block](https://github.com/L2jLiga/terser/blob/85b4ae85f07f307bf6bbd134ba868cb95561c74c/lib/compress.js#L5312)? It should be as simple as testing the node's type against `Number` (achieved in JS using `typeof`, no idea what Terser's API uses…)

**Comment by Conduitry** [comment]
Starting again from the original version of that function, I did arrive at this:

```javascript
    def_optimize(AST_New, function(self, compressor) {
        if (compressor.option("unsafe")) {
            var exp = self.expression;
            if (is_undeclared_ref(exp)) {
                if (
                    exp.name === "Array" && (
                        self.args.length === 0 ||
                        self.args.length === 1 && self.args[0] instanceof AST_Number && self.args[0].value <= 10
                    )
                ) {
                    const elements = [];
                    for (let i = 0; i < self.args.length && self.args[0].value; i++) elements.push(new AST_Hole);
                    return new AST_Array({elements});
                }
                switch (exp.name) {
                    case "Object":
                    case "RegExp":
                    case "Function":
                    case "Error":
                    case "Array":
                    return make_node(AST_Call, self, self).transform(compressor);
                }
            }
        }
        return self;
    });
```

which seems to work, but this still only optimizes stuff like `new Array(5)` and not `Array(5)`.

I can submit this as a PR along with a couple new tests, but I'm still not sure whether there's any good place that the shared parts of this logic should live so that we can optimize `Array(5)` as well.

**Comment by Alhadis** [comment]
> but this still only optimizes stuff like `new Array(5)` and not `Array(5)`.

This should be a separate optimisation, handled prior to this one:

~~~json
new Array(500) => Array(500);
~~~

It's literally 4 bytes less, each time.

**Comment by Conduitry** [comment]
👍 Makes sense, opened PR #314.

**Comment by Alhadis** [comment]
Make sure ASI won't screw with the `new Array => Array` transformation, BTW. This is still possible:

~~~js
someMethod()
new Array(5).fill(" ");

// Which becomes:
someMethod()
[,,,,].fill(" ");

// Which is treated as:
someMethod()[,,,,].fill(" "); // SyntaxError: Unexpected token ,

// Insert semicolon to fix
someMethod()
;[,,,,].fill(" ");
~~~

**Comment by fabiosantoscode** [comment]
Nice find :)

@Alhadis since terser operates on the AST level, it has already fixed all ESI issues by simply parsing. If you type `x` then a newline and then `[2]`, the parser correctly handles it like JavaScript does. Compression is a step which occurs after that.

**Comment by Alhadis** [comment]
Ace, that's relieving to know. 👍 Just wanted to make sure.
