### ISSUE TITLE
[bug] mangled property mutator's name only during invocation

### ISSUE THREAD

**Issue by huozhi** [terser-js/terser#322]
**Bug report**

property mutators created by babel helper createClass, is still been mangled.
this is a existed bug since uglify-js, I'm not sure if it's caused by dynamic created properties cannot been analyzed by terser AST

origin source: example.js
```js
class Apple {
    get val() { return 1 }
    mycall() { return 'method' }
}

var instance = new Apple()
console.log(instance.val)
console.log(instance.mycall())
```

babel config, transform class only
```json
{
  "plugins": [
    ["@babel/plugin-transform-classes", {
      "loose": true
    }]
  ]
}
```

**`terser` input**
babel it: example.es5.js

```js
function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

let Apple =
/*#__PURE__*/
function () {
  function Apple() {}

  var _proto = Apple.prototype;

  _proto.mycall = function mycall() {
    return 'method';
  };

  _createClass(Apple, [{
    key: "val",
    get: function () {
      return 1;
    }
  }]);

  return Apple;
}();

var instance = new Apple();
console.log(instance.val);
console.log(instance.mycall());
```

**Version (complete output of `terser -V`)**

3.17.0

**Complete CLI command or `minify()` options used**

```
terser [source] --mangle --mangle-props -b -o [output]
```

**`terser` output or error**

```js
function _defineProperties(e, n) {
    for (var t = 0; t < n.length; t++) {
        var r = n[t];
        r.t = r.t || false;
        r.i = true;
        if ("value" in r) r.o = true;
        Object.defineProperty(e, r.key, r);
    }
}

function _createClass(e, n, t) {
    if (n) _defineProperties(e.prototype, n);
    if (t) _defineProperties(e, t);
    return e;
}

let Apple = function() {
    function e() {}
    var n = e.prototype;
    n.s = function e() {
        return "method";
    };
    _createClass(e, [ {
        key: "val",
        get: function() {
            return 1;
        }
    } ]);
    return e;
}();

var instance = new Apple();

console.log(instance.u); // the getter name should still be val

console.log(instance.s());
```

**Expected result**

the getter/setter created by `_createClass`, defined their name as string, so they shouldn't been changed.

**Comment by huozhi** [comment]
Another example here is:

**terser input**
```js
var a = {propa: 1, propb: 2}

console.log(a.propa, a.propb, a.propc) // propc is an undefined property of a
```

with mangle-props option

**terser output**

```js
var a={o:1,p:2};console.log(a.o,a.p,a.l);
```

Question: should we keep the property name `propc` for safety? or we just mangle it randomly?
for the babel createClass case, is there anyway to detect it created properties dynamically?

**Comment by fabiosantoscode** [comment]
Terser isn't as smart as you think, and making it that smart is out of scope for the project. It does work with direct calls to `Object.defineProperty` but if that babel transform is using a wrapper function, no can do :)

**Comment by huozhi** [comment]
@fabiosantoscode what about the second example? `a.propc` is not a defined property, shall we still mangle it?

babel's class definition is too dynamic that we could probably ignore it. the second example is more like statically defined property was mangled by accident, isn't it? or it's hard to handle it with terser's AST parser? just curious 🤔
