### ISSUE TITLE
[bug] pure_funcs doesn't work with bind'ed functions

### ISSUE THREAD

**Issue by mikob** [terser-js/terser#323]
I am trying to optimize out binded `console.log` statements in minified js. I am binding `console.log` so that I can have an argument prepended by default.

The `pure_funcs` setting of terser doesn't appear to work with the binded function (see output below).

`drop_console` is even worse because it sets `this.log = void` and causes undefined function errors.

Am I missing something here? If an `x` function is pure, wouldn't it make sense that `x.bind` is pure?

Input:
```
class A {
    constructor() {
        this.log = console.log.bind(this, 'class A');
    }

    meth() {
        this.log('not optimized out');
        console.log('optimized out');
    }
}
```

terser config:
```
 drop_console     : false,
 pure_funcs       : ["console.log", "console.log.prototype.bind", "console.log.bind"],
```

Output:
```
class A{constructor(){this.log=console.log.bind(this,"class A")}meth(){this.log("not optimized out")}}:
```

**Comment by fabiosantoscode** [comment]
Terser doesn't support this, and it's not possible to do without running the actual code in some sort of VM. Terser has a very basic code evaluation functionality but it doesn't know about classes (which are just syntax sugar for functions anyway).
