### ISSUE TITLE
domprops missing definitions for MutationObserverInit

### ISSUE THREAD

**Issue by syranide** [terser-js/terser#327]
**Bug report or Feature request?**
BUG

**Version (complete output of `terser -V`)**
terser 3.14.1

**Description**
The domprops definitions for property mangling is incomplete with respect to MutationObserver. The properties of its options object is not defined in domprops.

See: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit

I'm assuming this file is automatically generated today, sadly the MutationObserverInit interface does not seem to be available in the DOM and its properties must be hardcoded?

PS. I can put up a PR for this, I just need to know what would be the right approach for it.

**Comment by fabiosantoscode** [comment]
Hey @syranide :) I'm shipping a new version with this issue fixed. Thanks for your report.
