### ISSUE TITLE
Module like code needs run terser twice to complete

### ISSUE THREAD

**Issue by tdzl2003** [terser-js/terser#331]
**Bug report or Feature request?**

Optimize request

**Version (complete output of `terser -V`)**

terser 3.17.0

**Complete CLI command or `minify()` options used**

--compress --mangle --toplevel

**`terser` input**

```
const a = (function() {
  function defaultFunction() {
    console.log('Foo');
  }
  return { default: defaultFunction };
})();

a.default();
```

**`terser` output or error**

```
(function(){return{default:function(){console.log("Foo")}}})().default();

```

**Expected result**

Got this output if run tenser again with output code:

```
console.log("Foo");
```

**`terser` input**

```
const a = (function() {
  return { a: 1, b: 2 };
})();
console.log(a.a);
```

**`terser` output or error**

```
const o={a:1,b:2};console.log(o.a);
```

**Expected result**

Got this output if run tenser again with output code:

```
console.log(1);
```

Is running tenser twice a right solution for these cases?

**Comment by Cyp** [comment]
Think it needs `{compress: {passes: 2}}` (or more). Not sure about the command line syntax.

**Comment by fabiosantoscode** [comment]
It's as @Cyp says. Instead of running the whole thing twice you can increase the number of passes by the compressor step.
