### ISSUE TITLE
[bug] collapse_vars produces broken esm output

### ISSUE THREAD

**Issue by TrySound** [terser-js/terser#333]
**Bug report or Feature request?**
bug

**Version (complete output of `terser -V`)**

terser 3.17.0

**Complete CLI command or `minify()` options used**
```
$ yarn terser file.js --compress --toplevel
```

**`terser` input**
```js
function shortOut() {
  return function() {};
}

var setToString = shortOut();

var _setToString = setToString;

export function baseRest() {
  return _setToString();
}

export { _setToString };
```

**`terser` prettified result**

```js
var _setToString,
  setToString = function() {};
export function baseRest() {
  return _setToString();
}
export { setToString as _setToString };
```

**Expected result**

```js
var setToString = function() {};
export function baseRest() {
  return setToString();
}
export { setToString as _setToString };
```

**Comment by fabiosantoscode** [comment]
I meant to take only a quick look, but this took me a lot longer than I expected...

The function that handles the `collapse_vars` option is called `collapse`

I'm guessing the issue is in the `extract_candidates` function. It doesn't take AST_Export into account.

**Comment by L2jLiga** [comment]
After investigations seems like this issue gone when `module: true`

command: `terser issue-333.js -c --module`
input same
output:
```javascript
var _setToString = function () {
};

export function baseRest() {
    return _setToString();
}

export { _setToString };
```

**Comment by TrySound** [comment]
@L2jLiga Is it master or latest published version? I still get broken output with latest version.

**Comment by L2jLiga** [comment]
I checked it on master branch, I guess (I have to recheck on which branch I was)

**Comment by L2jLiga** [comment]
Hmm, I was wrong.. I took input from https://github.com/terser-js/terser/pull/343 and it's work with `module: true` but given in this issue example does not

**Comment by TrySound** [comment]
I guess I oversimplified test

**Comment by L2jLiga** [comment]
That's it: https://github.com/terser-js/terser/pull/388
