### ISSUE TITLE
PR #288 removes access to AST

### ISSUE THREAD

**Issue by jacott** [terser-js/terser#351]
Bug report

By excluding the AST from the exports in PR #288 terser can no longer be used as an AST tool. This breaks two of my projects. Can we either restore the exports or create a separate bundle for using the AST?

**Comment by fabiosantoscode** [comment]
Great point, thank you for your report. The AST classes should be exported. Note that in Terser 4 the AST had some changes, we changed from the bespoke Dictionary class to ES6 Maps and Sets.
