### ISSUE TITLE
[bug] immediately invoked function and variable-name collision

### ISSUE THREAD

**Issue by freund17** [terser-js/terser#354]
**Bug report**

My second attempt on reproducing this bug... (first attempt: https://github.com/terser-js/terser/issues/352).
I think I got it this time around...
No idea what to title this issue though...

**Version (complete output of `terser -V` or specific git commit)**
terser 4.0.0

**Complete CLI command or `minify()` options used**
terser --compress

**`terser` input**

```js
(function(callback) {
  callback();
})(function() {
  window.used = function() {
    var A = window.foo,
      B = window.bar,
      C = window.foobar;

    return (function(A, c) {
      if (-1 === c) return A;
      return $(A, c);
    })(B, C);
  }.call(this);
});
```

**`terser` output**

```js
window.used = (function() {
  window.foo;
  var B = window.bar,
    C = window.foobar;
  return (function(A, c) {
    return $(A, c);
  })(B, C);
})();

```
*(Prettified)*

Notice the missing `if`.

**Expected result**

```js
window.used = (function() {
  window.foo;
  var B = window.bar,
    C = window.foobar;
  return -1 === C ? B : $(B, C);
})();
```
*(Prettified)*

**Comment by freund17** [comment]
With the outer function dropped - works:

**`terser` input**

```js
(function() {
  window.used = (function() {
    var A = window.foo,
      B = window.bar,
      C = window.foobar;

    return (function(A, c) {
      if (-1 === c) return A;
      return $(A, c);
    })(B, C);
  })();
})();
```

**`terser` output**

```js
window.used = (function() {
  window.foo;
  var B = window.bar,
    C = window.foobar;
  return -1 === C ? B : $(B, C);
})();
```
*(Prettified)*

**Comment by freund17** [comment]
With the unused variable, `A`, renamed to `X` - works:

**`terser` input**

```js
(function(callback) {
  callback();
})(function() {
  window.used = (function() {
    var X = window.foo,
      B = window.bar,
      C = window.foobar;

    return (function(A, c) {
      if (-1 === c) return A;
      return $(A, c);
    })(B, C);
  })();
});
```

**`terser` output**

```js
window.used = (function() {
  window.foo;
  var A,
    c,
    B = window.bar,
    C = window.foobar;
  return (A = B), -1 === (c = C) ? A : $(A, c);
})();
```
*(Prettified)*

**Comment by fabiosantoscode** [comment]
Oh my, this looks like a tough and serious one. Thanks for the repro :)

**Comment by roblan** [comment]
@fabiosantoscode looks a little like https://github.com/terser-js/terser/issues/294 and https://github.com/terser-js/terser/issues/308

and there is already MR for that: https://github.com/terser-js/terser/pull/320

**Comment by L2jLiga** [comment]
@roblan, #320 did not fix issue. I've just checked it, output same to master for given input

**Comment by fabiosantoscode** [comment]
Damn, I got my hopes up :(

**Comment by L2jLiga** [comment]
Hey, dont give it up!

**Comment by roblan** [comment]
Sorry :(

**Comment by L2jLiga** [comment]
PR created
