### ISSUE TITLE
Named functions declared as variable broken

### ISSUE THREAD

**Issue by HackbrettXXX** [terser-js/terser#361]
**Bug report or Feature request?**
Bug report
**Version (complete output of `terser -V` or specific git commit)**
4.0.0

**Complete CLI command or `minify()` options used**
minify()

**`terser` input**
```
import xy from 'foo'

var a = function a() {
  a()
}
```
**`terser` output or error**
```
import xy from"foo";var a=function o(){o()};
```
**Expected result**
```
import xy from"foo";var a=function a(){a()};
```
The name of the function and the recursive call are renamed incorrectly. Note that this error only occurs when there are imports.

**Comment by mischnic** [comment]
Happens without imports as well:
```js
var func = function func() {
	func();
};
```

Result of `echo "var func = function func() {func()};" | terser --mangle`:
`var func=function n(){n()};`

**Comment by L2jLiga** [comment]
What's the problem? It works perfectly fine (except `RangeError: Maximum call stack size exceeded`)

**command**: terser -cm input.js -o output.js

*input.js*:
```javascript
var func = function func() {
    func();
};

func();
```

*output.js*:
```javascript
var func = function n() {
    n();
};
func();
```

**Comment by HackbrettXXX** [comment]
The `n` in the recursive call is not defined. When you both define a function as variable as well as give it a name, the name of the function will not be a variable in the scope, which results in a "n is not defined" exception.

**Comment by L2jLiga** [comment]
Still did not get it

```javascript
const func = function e(i) {
  if (i > 5) return i;
  
  return e(++i);
}

func(0); // 6
```

**Comment by fabiosantoscode** [comment]
Maybe I'm being blind, but I can't see the problem either.

**Comment by fabiosantoscode** [comment]
Sorry, accidentally clicked close. 

The names of functions are declared in that function's scope and your code should function exactly the same. Please inform me if I'm incorrect.

**Comment by HackbrettXXX** [comment]
Yeah, you are right. Apparently the name of the function is in the scope within the function itself, but not outside. I can't reproduce the bug currently. Maybe it's an issue of webpack, actually. I got the error in a setting with rollup+terser and webpack afterwards and something in that pipeline produces incorrect code. At first I thought it this was a bug, but it appears it is not. So you can safely close the issue now ;) Sorry to bother you.
