### ISSUE TITLE
Multiple input sourcemaps

### ISSUE THREAD

**Issue by DominicTobias** [terser-js/terser#367]
**Bug report or Feature request?**

Feature request

Hi, thank you very much for maintaining terser. I am trying to concatenate multiple compiled JS files, each file has a source map e.g:

base.js + base.map.js
button.js + button.map.js

While we can specify multiple inputs, there doesn't appear to be a way to specify multiple source maps, is this correct? And if this is anything like uglify, it doesn't automatically pick up the maps from the `sourceMappingURL` comment unfortunately. Thanks

**Comment by L2jLiga** [comment]
Terser supports inline sourcemap

**Comment by DominicTobias** [comment]
Ok I’m going to close this but I don’t want to use inline source maps on the production bundles but still want to allow users to easily debug if they want. Anyway thanks, I will go for an alternative
