### ISSUE TITLE
[BUG] Fatal logic error when modify function argument by function define statement.

### ISSUE THREAD

**Issue by tinymins** [terser-js/terser#369]
**Bug report or Feature request?**
Bug report.

**Version (complete output of `terser -V` or specific git commit)**
terser 4.0.0

**Complete CLI command or `minify()` options used**
```
terser --compress -- test.js
```

**`terser` input**
```js
// test.js
var printTest = function (ret) {
    function ret() {
        console.log('Value after override');
    }
    return ret;
}('Value before override');

printTest();
```

**`terser` output or error**
```js
var printTest=function(ret){return"Value before override"}();printTest();
```

**Expected result**
```js
var printTest=function(ret){function ret(){console.log("Value after override")}return ret}();printTest();
```
or
```js
var printTest=function(ret){return function ret(){console.log("Value after override")}}();printTest();
```
or
```js
var printTest=function(){console.log("Value after override")};printTest();
```

**Link**
https://github.com/tinymins/terser/blob/issue-369/test/compress/issue-369.js
https://github.com/tinymins/terser/blob/issue-369/lib/compress/index.js#L1394

**Comment by fabiosantoscode** [comment]
Thank you very much for your report and the test!

Does this occur even if you specify different variable names for the argument `ret` and the function `ret`? If so this is high priority.

**Comment by tinymins** [comment]
@fabiosantoscode Yes, in my test file the argument name is `a`. https://github.com/tinymins/terser/blob/issue-369/test/compress/issue-369.js

**Comment by tinymins** [comment]
I'm not sure if I got a misunderstanding.

The bug is, if you assign the argument by define function statement, `unused` and `collapse_vars` config will cause compress error. The compressor think the define statement is an unused code block, and will remove it.

**Comment by fabiosantoscode** [comment]
Got it. This is low priority as I don't see too many people creating functions that are the same name as variables which already exist.

**Comment by tinymins** [comment]
Yep, I also think nobody will code like this.
But I triggered this bug by using a 3rd-party dev tools. I have to disable 'collapse_vars' config for using this tool.  https://eruda.liriliri.io/
I don't know why they write this kind of code:  https://github.com/liriliri/eruda/blob/8027c2435ca78f91927121e18faa78292b27e0bf/src/lib/util.js#L1272 , maybe it was created by `webpack` module wrapper?

**Comment by TrySound** [comment]
@fabiosantoscode lodash is one of the popular libraries. Similar problem with collapse_vars.
https://github.com/terser-js/terser/issues/333
