### ISSUE TITLE
key/option to use for mangle for unique output

### ISSUE THREAD

**Issue by mstruensee** [terser-js/terser#378]
**Feature request? Functionality Exists?**
**Version - latest**

I have been digging through the documentation and the source code trying to see if this is possible ... correct me if I am wrong ... Is there a flag I can pass (in my scenario I would like to pass package.version, or use the concept of "content-hash") so I can get a different minified/mangled output (params, function names, etc) each time during the build process?

Kind of like the debug flag where it would do something like ... 

> This would then mangle o.foo to o._$foo$XYZ_

If my use case is needed I can explain the issues were running into if needed.

**Comment by fabiosantoscode** [comment]
Hello there!

There is no such functionality, and I can't see the need for Terser to have this. We had a feature request to "write things" with the mangler, like `(function(h,e,y,a){ /* ... */ })(foo, bar, document, undefined)` which is also pretty unnecessary so I don't see Terser having that soon either.

**Comment by mstruensee** [comment]
Thanks for the info!
