### ISSUE TITLE
Terser doesn't compute constant string lengths

### ISSUE THREAD

**Issue by boris-petrov** [terser-js/terser#390]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

terser 3.17.0

**Complete CLI command or `minify()` options used**

`./node_modules/.bin/terser foo.js`

**`terser` input**

```javascript
console.log('foobar'.length);
```

**`terser` output or error**

Same as input

**Expected result**

```javascript
console.log(6);
```

This is a nice optimization that could be made I guess.

**Comment by fabiosantoscode** [comment]
This would be neat indeed, but I don't think the cost/benefit ratio pays off here. 

More code means more things to maintain, and unless it brings some real benefit to the final kb size I'm not going to do it.

**Comment by fabiosantoscode** [comment]
This would be neat indeed, but I don't think the cost/benefit ratio pays off here. 

More code means more things to maintain, and unless it brings some real benefit to the final kb size I'm not going to do it.

**Comment by boris-petrov** [comment]
Well, this is a win in both runtime performance and file size... not very much of course, but win-win.

Anyway, thank you for supporting Terser!
