### ISSUE TITLE
duplicated comment lines

### ISSUE THREAD

**Issue by gdh1995** [terser-js/terser#396]
**Terser version**: v4.1.2

**src**: `input.js`

``` javascript
var foo = {};
// this is a comment line
(foo.bar = window.WeakSet).foo_bar = 123
```

**command line**: `./node_modules/.bin/terser --comments=all input.js`

**real output**:

``` javascript
var foo={};
// this is a comment line
// this is a comment line
(foo.bar=window.WeakSet).foo_bar=123;
```

**expected output**:

``` javascript
var foo={};
// this is a comment line
(foo.bar=window.WeakSet).foo_bar=123;
```

**debugging**:

I find this bug is only triggered when the following line starts with a '`(`'.

**Comment by gdh1995** [comment]
The code below may be to blame: it breaks an assumption in output.js that `start.comments_before` and `last_end.comments_after` should be the same array (required by `._dumped === self` checks).

https://github.com/terser-js/terser/blob/e73277e82cfe756a35e424564ce3ab5da559c1d6/lib/parse.js#L2211-L2215

**Comment by fabiosantoscode** [comment]
Hey there :) I had a look at this but it looks tricky. I can't fix it so fast.

Your suggestion about what might be wrong is on point. Terser is a bit big. I don't know what that code is doing :S 

Thanks for the report.

**Comment by gdh1995** [comment]
Why not mark `._dumped` on every comment token? I think it has little speed impact and may reduce the logic amount you have to remind yourself of.

**Comment by gdh1995** [comment]
BTW, I found this issue because:
* at first, I used `passes=2`, but then terser would embed (and broadcast) some constant values to all places they're used
  * for example, I extracted a constant string literal to a closure, but terser would re-embed it
  * as a result, the result package size increased
* so I decided to call `terser.minify(code)` twice, and use an option of `mangle=null` at the second time
* however, I found I got 4 times of a single comment line when comments were kept.

So, I also wonder if terser may check gains before doing real embedding for variables.
