### ISSUE TITLE
Drop unused args for `new` calls

### ISSUE THREAD

**Issue by sirian** [terser-js/terser#398]
Is it possible to drop unused args of new calls? Like in function calls

**Version 4.1.2**

**Complete CLI command or `minify()` options used**
` terser -b -c --toplevel -m`

**`terser` input**
```javascript
function foo(){};
foo(123);
new foo(123);

class bar{}
new bar(123);
```

**`terser` output or error**
```
function n() {}
new n(123);
new class {}(123);
```

**Expected result**
```
function n() {}
new n();
new class {}();
```

**Comment by fabiosantoscode** [comment]
Terser doesn't run any of the code, so it's pretty hard to tell what arguments a function will take. Also, adding extra arguments is usually programmer error, so I don't want to add code to Terser to accomodate for that.
