### ISSUE TITLE
Newlines in evaluated RegExp literals are not escaped

### ISSUE THREAD

**Issue by RunDevelopment** [terser-js/terser#399]
**Bug report**

When compression code of the form `RegExp("any string literal")`, new lines are not escaped resulting is syntactically incorrect code.

**Version**
terser 4.1.2

**Complete `minify()` options**
```js
{
	compress: {
		unsafe: true
	}
}
```

**`terser` input**
```js
console.log(RegExp("\\\nfo\n[\n]o\\bbb"));
```

**`terser` output**
```js
console.log(/\
fo
[
]o\bbb/);
```

**Expected result**
```js
console.log(/\nfo\n[\n]o\bbb/);
```

**Comment by fabiosantoscode** [comment]
Fascinating. Thank you very much for your report. The toString method is trolling us :) `source` also has `\n` in it.

```
fabio@fabio-thinkpad ♥  node
> RegExp("\\\nfo\n[\n]o\\bbb")
/\
fo
[
]o\bbb/
```

You'll find that in node 12 only the first `\n` finds its way through.

I'll have a look, but this is yet another reason to save parsed regex values in string form.

**Comment by RunDevelopment** [comment]
Well, `toString` and `source` aren't really trolling. For the internal RegExp parser, a newline is just another regular character with no special meaning and `toString` and `source` just reflect that.

**Comment by fabiosantoscode** [comment]
True. But if you create the equivalent regular expression using a regex expression the newlines are escaped in the string representation. Inconsistent behaviour at least.

**Comment by RunDevelopment** [comment]
> Inconsistent behaviour at least.

That's true. That means that the expected result I gave is incorrect as the string representation of `/\nfo\n[\n]o\bbb/` and `RegExp("\\\nfo\n[\n]o\\bbb")` is different even though they are semantically the same.

In this case, the actual expected result would have to be:
```js
console.log(RegExp("\\\nfo\n[\n]o\\bbb"));
```

**Comment by fabiosantoscode** [comment]
I should've done this earlier, but I've taken this up with the V8 team.

https://bugs.chromium.org/p/v8/issues/detail?id=9618

I hope they fix it and we can continue relying on their RegExp representation. According to the spec we should see the escaped newline, not the real newline.

**Comment by fabiosantoscode** [comment]
I worked around this with a simple regex replace, since it will take another node version until this is fixed.

It should work fine with node 12.

**Comment by RunDevelopment** [comment]
Nice! Thank you!
