### ISSUE TITLE
Incorrect code generated with IIFE and variable name longer than 5 chars

### ISSUE THREAD

**Issue by christopherthielen** [terser-js/terser#401]
**This is a Bug report**

**Version (complete output of `terser -V` or specific git commit)**

```terser 4.1.2```

**Complete CLI command or `minify()` options used**

```npx terser --beautify -c dead_code=false < terser-input.js```

**`terser` input**

This input was extracted and simplified from some production code that was unexpectedly removed from our app via `dead_code`.  

```js
(function(factory) {
  window.mapValue = factory();
})(function () {
  return function mapValue(arg) {
    return (chars6 => {
      if (chars6) { return 1; }
    })(arg);
  };
});
```

**`terser` output or error**

```js
window.mapValue = function(arg) {
    return (chars6 => {
        if (void 0) return 1;
    })();
};
```

Note that `(void 0)` should be `chars6`

**Expected result**

```js
window.mapValue = function(arg) {
    return (chars6 => {
        if (chars6) return 1;
    })(arg);
};
```

----

Some important observations: 

- This code was wrapped in a webpack factory.  If I remove the factory wrapper from this snippet, terser generates the desired output.
- The incorrect code is generated if the parameter in the inner arrow function is 6 chars or longer.  If it's 5 characters or fewer, terser generates the desired output.
- If you turn off `collapse_vars`, terser generates the desired output.
- If you turn off `inline`, terser generates correct, but longer output.

---

Note the correct output when we rename the variable `chars6` to the 5 character symbol `chars`:

command line:

```
$ echo "(function(factory) {
  window.mapValue = factory();
})(function () {
  return function mapValue(arg) {
    return (chars => {
      if (chars) { return 1; }
    })(arg);
  };
});" | npx terser --beautify -c dead_code=false
```

output:

```
window.mapValue = function(arg) {
    return (chars => {
        if (chars) return 1;
    })(arg);
};
```

**Comment by fabiosantoscode** [comment]
Hello there! 

Thank you for the bug report and for sharing the results of your investigation!

This looks like a tricky one.

**Comment by L2jLiga** [comment]
Just tried on *latest master*, it looks like issue solved:

*CLI command*:
`terser issue.js --beautify -c`

*input*:
```javascript
(function(factory) {
    window.mapValue = factory();
})(function () {
    return function mapValue(arg) {
        return (chars6 => {
            if (chars6) { return 1; }
        })(arg);
    };
});
```

*output*:
```javascript
window.mapValue = function(arg) {
    return (chars6 => {
        if (arg) return 1;
    })();
};
```

output suboptimal, but correct

**Comment by fabiosantoscode** [comment]
This was probably your patch @L2jLiga :)
