### ISSUE TITLE
Anonymous functions cannot be parsed: Terser.parse()

### ISSUE THREAD

**Issue by 0b10** [terser-js/terser#403]
**Bug report or Feature request?**
Bug report

"Note: sub-optimal but correct code is NOT a bug."
Anonymous functions may be sub-optimal, but shouldn't it still parse?

**Version (complete output of `terser -V` or specific git commit)**
terser 4.1.2

**Complete CLI command or `minify()` options used**
N/a

**`terser` input**

Example 1
```js
console.log(function() {}.toString())
// function () { 
//   $_$wf(1); 
// } 
Terser.parse(function() {}.toString()) // Unexpected token: punc (()
```

Example 2
```js
const obj = {
  fn: function() { }
};
console.log(obj.fn.toString())
// function () {
//   $_$wf(1); 
// }
Terser.parse(obj.fn.toString()) // Unexpected token: punc (()
```

Example 3
```js
const fn2 = function() { }
console.log(fn2.toString())
// function () {
//   $_$wf(1); 
// } 
Terser.parse(fn2.toString())  // Unexpected token: punc (()
```

**`terser` output or error**

Unexpected token: punc (()

**Expected result**

An AST_Node object

**Comment by L2jLiga** [comment]
Hello there, nothing wrong with Terser.

You can use anonymous functions as arguments, in IIFE, but you can't declare Function statement without name by specification.

**Comment by fabiosantoscode** [comment]
Hey there :) anonymous functions are expressions, not statements. Terser is failing to parse because an anonymous function expression is not a valid JS program. If you want to parse an anonymous function you need to wrap it in parentheses.
