### ISSUE TITLE
RegExp.prototype.test not detected as pure function

### ISSUE THREAD

**Issue by nolanlawson** [terser-js/terser#405]
**Bug report or Feature request?** Feature request

**Version (complete output of `terser -V` or specific git commit)** 4.1.2

**Complete CLI command or `minify()` options used** `terser -mc`

**`terser` input**

```js
(function () {
  const IS_IPHONE = /iPhone/.test(navigator.userAgent)
  const IS_ANDROID = /Android/.test(navigator.userAgent)
  const IS_CHROME = /Chrome/.test(navigator.userAgent)

  console.log(IS_CHROME)
})()
```

**`terser` output or error**

```js
!function(){/iPhone/.test(navigator.userAgent),/Android/.test(navigator.userAgent);const t=/Chrome/.test(navigator.userAgent);console.log(t)}();
```

**Expected result**

```js
!function(){const o=/Chrome/.test(navigator.userAgent);console.log(o)}();
```

I would expect that the first and second regex `.test()` calls could be removed, because `RegExp.prototype.test()` has no side effects.

**Comment by fabiosantoscode** [comment]
You could modify `RegExp.prototype.test` to do anything you like, including side effects. I can't fix this without an unsafe option, and I don't think this warrants a new option.

thanks for the report!
