### ISSUE TITLE
function/object inlining breaks loose equality checks on default parameters that are inlined

### ISSUE THREAD

**Issue by MarshallOfSound** [terser-js/terser#407]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

`4.1.2`

**Complete CLI command or `minify()` options used**

```bash
terser --parse=acorn entry.js -c toplevel
```

**`terser` input**

```js
const defaultArg = input => input;

const fn = (arg = defaultArg) => arg

if(fn() !== fn()) throw new Error('Something is broken');
```

**`terser` output or error**

```js
const fn=(arg=(input=>input))=>arg;if(fn()!=fn())throw new Error("Something is broken");
```

Beautified for readability

```js
const fn = (arg = (input => input)) => arg;

if (fn() != fn()) throw new Error("Something is broken");
```

**Expected result**

The default param if it isn't a primitive (is an object/function) shouldn't be inlined.  E.g.

```js
const defaultArg = input => input;
const fn = (arg = defaultArg) => arg;

if (fn() != fn()) throw new Error("Something is broken");
```

If you run the input code it exits cleanly, if you run the code terser outputs it throws an error.  The code is correct but the over-eager inlining of the top level function causes issues.

**Comment by sokra** [comment]
This is not directly related to default arguments. Seems like any case of inlining functions into other functions is broken:

``` js
const a = input => input;

const fn = () => a;

if(fn() !== fn()) throw new Error('Something is broken');
```

``` js
if((n=>n)!=(n=>n))throw new Error("Something is broken")
```

---

This is also not directly related to the `toplevel` option as you could put the code into a IIFE to cause the problem.

**Comment by MarshallOfSound** [comment]
@sokra Haha your timing is perfect, I just came here to add I have a repro without `toplevel`.

```
const assert = (c) => { if (!c) throw new Error('Assertion failed') }
function main() {
  const a = () => 1;
  return (b = a) => {
    return b;
  }
}

const fn = main()
assert(fn() == fn())
```

I'm surprised this isn't causing more issues with things like react hooks (that's where I first discovered it).

**Comment by fabiosantoscode** [comment]
I'm also surprised this hasn't caused bigger issues.

Well, I can't see a way of fixing this without nerfing function inlining somewhat :/ but hey, here we go :)

**Comment by fabiosantoscode** [comment]
Nerfing is indeed going to happen but I opened a new issue to try and minimize that.
