### ISSUE TITLE
Minification inadvertently converts ISO-8859-1 non-ASCII characters to UTF-8

### ISSUE THREAD

**Issue by SetTrend** [terser-js/terser#410]
# Bug Report

Non-ASCII characters in a string literal from a UTF-8 JavaScript file are inadvertently converted to their UTF-8 counterparts. Minifying string literals in a UTF-8 Javascript file should not alter the text's non-ASCII characters.

- Operating system: Windows 10x64
- Node version: v10.3.0
- NPM version: 6.1.0
- Terser version: terser 4.0.0

### Code

See [this sample repository](/SetTrend/encoding-issue).

### How Do We Reproduce?

See this GitHub thread for full discussion: /webpack-contrib/terser-webpack-plugin/issues/107

**Comment by fabiosantoscode** [comment]
Everything is working as designed. The latin-1 character ä happens to be identified with the same code in unicode. The strings are exactly the same, but the actual `ä` accounts for less bytes in the output. Which in terser is utf-8 and there will never be an option to change that.

If you don't want Terser to convert things to unicode for you there's an output option for that, `ascii_only`!

```
fabio@fabio-thinkpad ♥  echo 'x(`\u00E4`)' | ./bin/uglifyjs -mc 
x("ä");
fabio@fabio-thinkpad ♥  echo 'x(`\u00E4`)' | ./bin/uglifyjs -mc -b ascii_only=true
x("\xe4");
```

Thanks for reporting and have a great weekend :D

**Comment by SetTrend** [comment]
@fabiosantoscode 👍 

Thank you for the hint!

Yet, your statement is not correct. For anything beyond ASCII (which does **not** include any character point beyond `0x7f,` as ASCII is a 7 bit character set, so the <kbd>ä</kbd> character is **not** included in ASCII) UTF-8 is defined to add a codepage switch control character plus a second character within that selected codepage. See [this page](https://en.wikipedia.org/wiki/UTF-8#Description) for quick reference.

**Comment by fabiosantoscode** [comment]
Sorry for the misunderstanding. Had to pull out python to reliably reproduce this.

```
fabio@fabio-thinkpad ♥  echo '\u00E4' | ./bin/uglifyjs 
ä;
fabio@fabio-thinkpad ♥  echo '\u00E4' | ./bin/uglifyjs | hexdump
0000000 a4c3 0a3b                              
0000004
fabio@fabio-thinkpad ♥  python3
Python 3.7.3 (default, Mar 30 2019, 15:09:56) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from binascii import unhexlify
>>> unhexlify('a4c30a3b')
b'\xa4\xc3\n;'
>>> _.decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 0: invalid start byte

```

**Comment by SetTrend** [comment]
Thanks for reopening, @fabiosantoscode .

Please pardon me for nit-picking, but due to the **little-endian** encoding of your hexdump ...

```
0000 c3 a4 3b 0a
            ^  ^
            |  |
    semicolon  |
               line-feed
```
was output by your tool in word notation as:

```
0000 a4c3 0a3b
```

So, your `unhexlify` command correctly should have read: `unhexlify('c3a43b0a')`.

**Comment by SetTrend** [comment]
@evilebottnawi,

I just noticed that the `ascii_only` option is not supported by [webpack-contrib/terser-webpack-plugin](/webpack-contrib/terser-webpack-plugin).

**Comment by fabiosantoscode** [comment]
@SetTrend terser-webpack-plugin supports all Terser options through its "terserOptions" object. It might be a bit confusing because Terser's options are separated into several objects, but they support it all :)

WRT the bug, thanks for letting me know about `hexdump`. I have to find a new hex tool :) I rarely do any binary stuff though.

Anyway, the command you specified produces a valid UTF-8 string:

```
>>> unhexlify('c3a43b0a')
b'\xc3\xa4;\n'
>>> unhexlify('c3a43b0a').decode('utf-8')
'ä;\n'
```

So there's a `C3`, a `A4` (besides the semicolon and the newline which are ASCII-compatible), which I went to node to convert to binary:

```
> 0xc3.toString(2)
'11000011'
> 0xa4.toString(2)
'10100100'
```

As you can see the first byte starts with `110` which means the code point will occupy 2 bytes. The next byte starts with `10` as specified in the wiki page you linked.

So it appears to me like there is no bug here.

**Comment by SetTrend** [comment]
@fabiosantoscode:

Oh oh, it seems we're talking at cross purposes here.

Let me put it in some other, perhaps more specific words:

The fact that Terser converts a valid 8-Bit glyph into a UTF-8 character is the bug. The bug is _not_, however, that the converted character is a valid UTF-8 character in the end. The bug is that strings are converted at all.

Terser may not change any content of strings or regular expressions, because these are not JavaScript, they are plain opaque code strings that must not be tampered with; regardless what codepage the JavaScript code might be in. Strings and regular expressions must never be altered by Terser in any way.

While regular expressions are not touched by Terser (which is as expected), strings are only left untouched when the `ascii_only` option is set to true. The only reasonable way to deal with strings is to keep `ascii_only` option is set to true, so the most simple solution would be to change it's default setting to `true`.
