### ISSUE TITLE
Should not generate source map file if url=inline

### ISSUE THREAD

**Issue by nikolay-borzov** [terser-js/terser#418]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser 4.1.4

**Complete CLI command or `minify()` options used**
`terser bar.js -c --source-map "url=inline" -o bar.min.js`

**`terser` input**
bar.js
```
function bar(x) {
  return `bar${x}`;
}

module.exports = bar;
```

**`terser` output or error**
bar.min.js
```
function bar(x){return`bar${x}`}module.exports=bar;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImJhci5qcyJdLCJuYW1lcyI6WyJiYXIiLCJ4IiwibW9kdWxlIiwiZXhwb3J0cyJdLCJtYXBwaW5ncyI6IkFBQUEsU0FBU0EsSUFBSUMsR0FDWCxZQUFhQSxJQUdmQyxPQUFPQyxRQUFVSCJ9
```
bar.min.js.map
```
{"version":3,"sources":["bar.js"],"names":["bar","x","module","exports"],"mappings":"AAAA,SAASA,IAAIC,GACX,YAAaA,IAGfC,OAAOC,QAAUH"}
```

**Expected result**

`bar.min.js.map` should not be created because the source map is inlined in `bar.min.js`

**Comment by fabiosantoscode** [comment]
Thanks! I haven't noticed this :)
