### ISSUE TITLE
Prepend is lost

### ISSUE THREAD

**Issue by alexpopovme** [terser-js/terser#436]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V` or specific git commit)**
terser 4.2.0

**Complete CLI command or `minify()` options used**

`npx terser test.prepend.js -c -m --mangle-props=keep_quoted -o test.min.js`

**`terser` input**

```
// test.prepend.js
let d = document.createElement('div')
let el = document.getElementById('id')
let obj = { var1: '', 'var2': ''}
el.appendChild(d)
el.prepend(d)
el.append(d)
```

**`terser` output**

```
// test.min.js
let d=document.createElement("div"),el=document.getElementById("id"),obj={l:"",var2:""};el.appendChild(d),el.o(d),el.append(d);
```

**Expected result**

```
// test.min.js
let d=document.createElement("div"),el=document.getElementById("id"),obj={l:"",var2:""};el.appendChild(d),el.prepend(d),el.append(d);
```
Prepend is lost

**Comment by fabiosantoscode** [comment]
Thanks!

If you notice any other native browser props being lost to --mangle-props, do edit `tools/domprops.js` and send a PR ;)

**Comment by fabiosantoscode** [comment]
Closed in https://github.com/terser-js/terser/commit/34ac82692ff7d335b6177ed7724e4db5fc8623f9
