### ISSUE TITLE
Minification of unicode escape sequences creates an offset in source maps

### ISSUE THREAD

**Issue by jessecrossen** [terser-js/terser#437]
**Bug report or Feature request?**

Bug report.

**Version (complete output of `terser -V` or specific git commit)**

```
$ npx terser -V
terser 4.2.0
undefined
```

**Complete CLI command or `minify()` options used**

```
$ npx terser --source-map "includeSources" --output index.min.js index.js
```

**`terser` input**

```
const A = 1;
const B = 2;
const escapes = '\u5b64\u5c71\u5bfa\u5317\u8d3e\u4ead\u897f / \u6c34\u9762\u521d\u5e73\u4e91\u811a\u4f4e / \u51e0\u5904\u65e9\u83ba\u4e89\u6696\u6811 / \u8c01\u5bb6\u65b0\u71d5\u5544\u6625\u6ce5 / \u4e71\u82b1\u6e10\u6b32\u8ff7\u4eba\u773c / \u6d45\u8349\u624d\u80fd\u6ca1\u9a6c\u8e44 / \u6700\u7231\u6e56\u4e1c\u884c\u4e0d\u8db3 / \u7eff\u6768\u9634\u91cc\u767d\u6c99\u5824';
const C = 3;
const D = 4;
const E = 5;
const F = 6;
const G = 7;
const H = 8;
```

**`terser` output or error**

`index.min.js`
```
const A=1;const B=2;const escapes="孤山寺北贾亭西 / 水面初平云脚低 / 几处早莺争暖树 / 谁家新燕啄春泥 / 乱花渐欲迷人眼 / 浅草才能没马蹄 / 最爱湖东行不足 / 绿杨阴里白沙堤";const C=3;const D=4;const E=5;const F=6;const G=7;const H=8;
```

`index.min.js.map`
```
{"version":3,"sources":["index.js"],"names":["A","B","escapes","C","D","E","F","G","H"],"mappings":"AAAA,MAAMA,EAAI,EACV,MAAMC,EAAI,EACV,MAAMC,QAAU,gFAChB,MAAMC,EAAI,EACV,MAAMC,EAAI,EACV,MAAMC,EAAI,EACV,MAAMC,EAAI,EACV,MAAMC,EAAI,EACV,MAAMC,EAAI","sourcesContent":["const A = 1;\nconst B = 2;\nconst escapes = '\\u5b64\\u5c71\\u5bfa\\u5317\\u8d3e\\u4ead\\u897f / \\u6c34\\u9762\\u521d\\u5e73\\u4e91\\u811a\\u4f4e / \\u51e0\\u5904\\u65e9\\u83ba\\u4e89\\u6696\\u6811 / \\u8c01\\u5bb6\\u65b0\\u71d5\\u5544\\u6625\\u6ce5 / \\u4e71\\u82b1\\u6e10\\u6b32\\u8ff7\\u4eba\\u773c / \\u6d45\\u8349\\u624d\\u80fd\\u6ca1\\u9a6c\\u8e44 / \\u6700\\u7231\\u6e56\\u4e1c\\u884c\\u4e0d\\u8db3 / \\u7eff\\u6768\\u9634\\u91cc\\u767d\\u6c99\\u5824';\nconst C = 3;\nconst D = 4;\nconst E = 5;\nconst F = 6;\nconst G = 7;\nconst H = 8;"]}
```

**Expected result**

The bug is that any lines in the source map after the unicode escape sequence are offset by some amount. The easiest way I found to see this is to resolve columns from the minified file using the [source-map cli package](https://github.com/mozilla/source-map), which I installed with `npm install -g source-map`.

A line before the escape sequences resolves correctly: 
```
$ source-map resolve index.min.js.map 1 11
Maps to index.js:2:0 

const B = 2;
^
```

A line just after the escape sequence resolves incorrectly to the final line:
```
$ source-map resolve index.min.js.map 1 171
Maps to index.js:9:6 (H)

const H = 8;
      ^
```

The expected output would have been:
```
$ source-map resolve index.min.js.map 1 171
Maps to index.js:4:0

const C = 3;
^
```

A workaround for this is to use the `ascii_only` output option, which will leave the escape sequences as-is instead of converting them into UTF-8 encoding, and the offset will not appear.

I'm happy to try and fix this or contribute to a fix, but am posting this issue first to comply with the guidelines.

**Comment by fabiosantoscode** [comment]
Pesky unicode errors. There's something that assumes the length of the string stays the same, that's what!

I would appreciate a PR indeed :)

**Comment by jessecrossen** [comment]
After trying to write a failing test for this, it seems it's not actually an error.  I was getting the column count in the final file by looking at it in Visual Studio code, which apparently counts a single Chinese character as taking up two columns instead of one. In case it's of any interest, here's the (passing) test code I added to `sourcemaps.js`, and the column to look up comes out as 120 instead of 171:

```
        it("Should work with unicode escape sequences", function() {
            var code = [
                "const A = 1;",
                "const B = 2;",
                "const escapes = '\u5b64\u5c71\u5bfa\u5317\u8d3e\u4ead\u897f / \u6c34\u9762\u521d\u5e73\u4e91\u811a\u4f4e / \u51e0\u5904\u65e9\u83ba\u4e89\u6696\u6811 / \u8c01\u5bb6\u65b0\u71d5\u5544\u6625\u6ce5 / \u4e71\u82b1\u6e10\u6b32\u8ff7\u4eba\u773c / \u6d45\u8349\u624d\u80fd\u6ca1\u9a6c\u8e44 / \u6700\u7231\u6e56\u4e1c\u884c\u4e0d\u8db3 / \u7eff\u6768\u9634\u91cc\u767d\u6c99\u5824';",
                "const C = 3;",
                "const D = 4;",
                "const E = 5;",
                "const F = 6;",
                "const G = 7;",
                "const H = 8;"
            ].join("\n");
            var result = UglifyJS.minify(code, {
                compress: false,
                mangle: false,
                sourceMap: {
                    content: "inline",
                    includeSources: true
                }
            });
            if (result.error) throw result.error;
            // the column the second line is on in the minified output
            var column = result.code.indexOf('const C');
            var consumer = new SourceMapConsumer(result.map);
            var location = consumer.originalPositionFor({ line: 1, column: column });
            assert.strictEqual(location.line, 4);
            assert.strictEqual(location.column, 0);
        });
```

It's possible that some Javascript parsers would make the same mistake, so my recommended workarounds are setting `output.ascii_only` to true, which should mitigate encoding problems in general, and `output.semicolons` to false, which prevents any offsets from accumulating further than a single line.

**Comment by fabiosantoscode** [comment]
Thank you very much for looking into this!

Nice test btw *yoink*
