### ISSUE TITLE
Arrow function with no arguments to single unused argument

### ISSUE THREAD

**Issue by pynnl** [terser-js/terser#439]
**Bug report or Feature request?**
Feature request

**`terser` input**
```javascript
() => {}
```

**`terser` output or error**
```javascript
a=>{}
```
P/S: I'm not sure if there's any downsides, please correct me.

**Comment by fabiosantoscode** [comment]
The problem with this is that it changes the function's `length` property. Also the gain is very low.

So this kind of change shouldn't go in.

**Comment by dy** [comment]
What about
```
(e=>{var[r]=e;return r})
```
vs
```
(([r])=>r)
```
?
