### ISSUE TITLE
How to programatically apply terser after browserify bundle

### ISSUE THREAD

**Issue by nolimitdev** [terser-js/terser#89]
I have working code below. Uglifyify is used to get smaller output by processing files individually instead of just the entire bundle. According to uglifyify doc we should also apply minification to whole bundle to get best result. Nowadays we should use terser minifier instead of uglify-js and uglify-es (btw. uglifyify also uses terser) but terser's doc does not show example how to use with combination of browserify bundle/pipe.

```javascript
browserify("./main.js")
  .transform(vueify)
  .transform(babelify)
  .transform({ global: true }, envify())
  .transform({ global: true }, uglifyify)
  .bundle()
  // I would like to apply terser here
  .pipe(fs.createWriteStream("./build.js"))
```

**Comment by kzc** [comment]
Out of scope for Terser. This is a question for the Browserify project.

**Comment by goto-bus-stop** [comment]
You can use https://github.com/goto-bus-stop/minify-stream, it uses terser by default:

```js
var minify = require('minify-stream')

browserify()
  /* ... */
  .bundle()
  .pipe(minify())
  .pipe(fs.createWriteStream(/* ... */))
```

**Comment by kzc** [comment]
This issue can be closed.

**Comment by nolimitdev** [comment]
@goto-bus-stop thank you for minify-stream. My task for processing scripts is now easier and shorter than using terser outside of stream - I had to do read builded JS file on stream write finish and manually handle sourcemaps for terser (read origin map and write new one) and write builded JS file again.
