### ISSUE TITLE
scope of function parameter's default value is wrong

### ISSUE THREAD

**Issue by kzc** [terser-js/terser#91]
Test case borrowed from https://github.com/babel/babel/issues/4173:

```
$ terser -V
terser 3.8.1
```
```
$ cat b4173.js
let foo = 'outer';
function bar(func = x => foo) {
    let foo = 'inner';
    console.log(func()); // outer
}
bar();
```
Expected:
```
$ cat b4173.js | node-v10.4.1 
outer
```
Actual:
```
$ cat b4173.js | terser -c toplevel | node-v10.4.1 
[stdin]:1
!function(func=(x=>foo)){let foo="inner";console.log(func())}();
                   ^
ReferenceError: foo is not defined
```
```
$ cat b4173.js | terser -m | node-v10.4.1 
[stdin]:1
let foo="outer";function bar(o=(o=>e)){let e="inner";console.log(o())}bar();
                                   ^
ReferenceError: e is not defined
```
```
$ cat b4173.js | terser -cm --toplevel | node-v10.4.1 
[stdin]:1
!function(n=(n=>o)){let o="inner";console.log(n())}();
                ^
ReferenceError: o is not defined
```

Related bug: https://github.com/mishoo/UglifyJS2/issues/2662

**Comment by kzc** [comment]
The issue is probably in `figure_out_scope` should anyone decide to work on it:

https://github.com/fabiosantoscode/terser/blob/e239197df59cd860cf9c1764a12fc0fa691a0581/lib/scope.js#L104-L343

Related bug: https://github.com/mishoo/UglifyJS2/issues/2662

**Comment by kzc** [comment]
Just a word of caution to any potential PR submitter - this is not an easy fix, and an incorrect one would break minified code in very subtle ways. The current code assumes that each node's scope coincides with the AST tree structure - which is not the case here. A correct fix would involve starting the resolution scope chain of any `AST_SymbolRef` only within `AST_DefaultAssign.right` subtrees of `AST_Lambda.argnames` to the *parent* of the `AST_Lambda` in question. The trick is restraining the resolution fix to the correct occurrences of these symbols while implementing an efficient solution that does not significantly slow down `figure_out_scope` in the general case.

**Comment by tomwetjens** [comment]
I am using CryptoJS which gets processed by terser through webpack. And I appear to be having a similar issue. I took the CryptoJS source code and managed to narrow it down to this case:
`(function (root, factory) {
  root.CryptoJS = factory()
})(this, function () {
  var CryptoJS = CryptoJS || function (Math) {
    var C = {};
    C.demo = function(n) {
      return Math.ceil(n);
    };
    return C;
  }(Math);
  return CryptoJS
});


var result = this.CryptoJS.demo(1.3);
console.log(result);
`

I run it through terser manually: terser -c -- demo.js
And when I run it:

Expected:
2

Actual:
TypeError: Cannot read property 'ceil' of undefined

Could this be the same issue as mentioned above?

**Comment by kzc** [comment]
@tomwetjens #91 is specifically an ES6 bug dealing with the scope of default parameters. Your example is ES5 and is a different bug in the `inline=3` compress setting. Please create a new issue for it.

**Comment by tomwetjens** [comment]
@kzc thanks, I opened #156
