### ISSUE TITLE
move to organization

### ISSUE THREAD

**Issue by DanielRuf** [terser-js/terser#95]
I think we should move this to an organization to increase the truck factor, easo collaboration and contribution and prevent the same things that happen(ed) to the original uglifyjs project where the whole project is dependent of just one person.

**Comment by TrySound** [comment]
There are a few people in uglifyjs. Same could happen in monorepo too. Practically org doesn't make sense with one package.

**Comment by DanielRuf** [comment]
> Practically org doesn't make sense with one package.

I see it differently as a private account has other rights than an org (maintainers / owners, contributors, groups).

**Comment by kzc** [comment]
The truck factor is not improved by an organization in this case because the core PR contributers are a strict subset of the last project - just one individual at this time - the truck driver @fabiosantoscode. Until others step up demonstrating knowledge of the code base and ability to make fixes and new features it's a moot point.

I've yet to see a viable way to sponsor open source projects other than having a large company commit fulltime staff resources to it.

**Comment by DanielRuf** [comment]
> I've yet to see a viable way to sponsor open source projects other than having a large company commit fulltime staff resources to it.

Do you mean solutions like OpenCollect?

**Comment by kzc** [comment]
With just a handful of notable exceptions, I don't think it's possible to raise enough money to sustain open source development for libraries through micropayments. Developers by in large are cheap and don't place any value in the code they use. The most successful open source projects are funded by Fortune 500 companies with internal staff. They have to produce and maintain such generic infrastructure software anyway and they can lower their maintenance cost somewhat by open sourcing such projects.

**Comment by fabiosantoscode** [comment]
I certainly like the idea of an organisation. It makes the project seem more official and might attract maintainers. I'll do it when I get the time.

**Comment by fabiosantoscode** [comment]
![screenshot from 2018-09-21 18 36 43](https://user-images.githubusercontent.com/1611595/45896896-6f6a8f80-bdcd-11e8-9004-88734a840688.png)

Looks like the "terser" username is already taken. Is that you vasily.anonimov? :D

**Comment by TrySound** [comment]
Try terserjs. It's free

**Comment by TrySound** [comment]
Since org is a part of global namespace it's a good practice to specify language in name IMO. So js suffix should go fine.

**Comment by fabiosantoscode** [comment]
Done!

**Comment by TrySound** [comment]
Great! Did you contact github to remove fork effect?

**Comment by kzc** [comment]
>  lose all issue/PR/etc history, so that's not ideal.

That would be a showstopper. 

Many Terser issues, PRs, and commit comments contain `#NNNN` references to the old UglifyJS2 repo.  Those links would break.

**Comment by kzc** [comment]
> I believe if you contact GitHub support they can disconnect it on their end so this repo won't show up as a fork.

Same concern with UglifyJS2 repo `#NNNN` references as my last comment.

**Comment by fabiosantoscode** [comment]
I've just requested that the repository be un-forked!

**Comment by DanielRuf** [comment]
Well, that is supposed to happen when they do it. Because the old history has no reference to the original repository anymore.

**Comment by kzc** [comment]
I recognize that's what was expected by de-forking, but this resulted in a loss of github functionality that I used. Terser's history is naturally tied to UglifyJS2. What was the point of this de-forking exercise?
